---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 10m
  chart:
    spec:
      chart: headlamp
      version: "0.28.1"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # OIDC configuration for Authentik
    config:
      oidc:
        clientID: headlamp
        issuerURL: https://auth.almckay.io/application/o/headlamp/
        scopes: "openid profile email"
        # Use external secret for OIDC credentials
        externalSecret:
          enabled: true
          name: headlamp-oidc
      pluginsDir: /build/plugins

    # Init container to load Flux plugin
    initContainers:
      - name: flux-plugin
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        command:
          - /bin/sh
          - -c
          - |
            mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        volumeMounts:
          - name: headlamp-plugins
            mountPath: /build/plugins
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false

    # Volume for plugins
    volumeMounts:
      - name: headlamp-plugins
        mountPath: /build/plugins

    volumes:
      - name: headlamp-plugins
        emptyDir: {}

    # Ingress configuration
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: cluster.almckay.io
          paths:
            - path: /
              type: Prefix
      tls:
        - secretName: headlamp-tls
          hosts:
            - cluster.almckay.io

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    # Cluster role binding (needed for cluster-wide access)
    clusterRoleBinding:
      create: true
