apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:/bPNX7M0TkKL6Zb1E4YRagX7q+ooklxNamIrVXj+IWVus3AMJdqMFw==,iv:/ZLwf8YLuns/2itAWNlvxNeTFVa0xiTjVmf5FXV6bNc=,tag:2lWuhViSVThWYwZQDgHHnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRnp4RFNpOTFIaWJjTis2
            d29TVE9HejdiaDNQQTlhdm91ZFF1YzBjYVNJClJURzk5amFZbjhGQzRzM2l1aDRC
            Ry8rQUI4RWY0MEhId25CdkpNaVIrbXMKLS0tIGZpTVcwZDF3eXhXb1ZSWCtySHZ1
            UVBIM3prTytMR2JRamZ6cHFwQUE4ejQK5+/aWpTCSIDLn4skSWmoCtFlnE7st0Fm
            OS34adctSSoruCCNbKJ/RVjuiajtb9B+F9HirQYAM6lGTq81KFKXZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T23:45:41Z"
    mac: ENC[AES256_GCM,data:GcCHwLY5VDK1zaH/f8+DU+oexOs8fk5IR6grxFSYk1fy36XpqchDu8rA89+GctyIVe2Pallq2hVcM/8AAl0Qf/TI6SzmhmpLmzeqMUIWQiPOEFTeoZQGvfIEu+JGkTv8G7tqR7PIMHJzPz3KhanWgWSKz9Q5Q/7f4uFd5jwsiFg=,iv:lBS0B2ljNvrRzSxrBaDBcgHghfNbo8g7+Fh14fzf3HU=,tag:W6n0vThl9FZb7AvG1r4Gwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
