---
# Deploy gpt-oss-20b model using DynamoGraphDeployment CRD
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: gpt-oss-20b
  namespace: dynamo
spec:
  # Persistent volume for model storage
  pvcs:
    - name: model-storage
      size: 100Gi

  # Service definitions
  services:
    # OpenAI-compatible API frontend
    Frontend:
      replicas: 1
      envs:
        - name: MODEL_NAME
          value: openai/gpt-oss-20b

    # vLLM Worker for inference
    VllmWorker:
      replicas: 1
      envs:
        - name: MODEL_NAME
          value: openai/gpt-oss-20b
        - name: TENSOR_PARALLEL_SIZE
          value: "1"
        - name: MAX_MODEL_LEN
          value: "8192"
        - name: GPU_MEMORY_UTILIZATION
          value: "0.9"
      volumeMounts:
        - name: model-storage
          mountPoint: /models
