---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grove
  namespace: dynamo
spec:
  interval: 10m
  dependsOn:
    - name: dynamo-platform
  chart:
    spec:
      chart: grove
      sourceRef:
        kind: HelmRepository
        name: ai-dynamo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Grove operator configuration
    operator:
      enabled: true
