---
# Deploy Qwen3-0.6B model using DynamoGraphDeployment CRD
# Uses vLLM backend with OpenAI-compatible API
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: qwen-vllm
  namespace: dynamo
spec:
  services:
    Frontend:
      dynamoNamespace: qwen-vllm
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.7.0

    VllmDecodeWorker:
      envFromSecret: hf-token-secret
      dynamoNamespace: qwen-vllm
      componentType: worker
      replicas: 1
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.7.0
          workingDir: /workspace/examples/backends/vllm
          command:
            - python3
            - -m
            - dynamo.vllm
          args:
            - --model
            - Qwen/Qwen3-0.6B
