apiVersion: v1
kind: Secret
metadata:
    name: nas-smb-creds
    namespace: nas-storage
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DqM=,iv:FuxMNz5z/0aylw9zb6Eo19tbRB9GPyHuOL+JF0XKSK8=,tag:KnBaJk74X4ZgcswhAnXrHw==,type:str]
    password: ENC[AES256_GCM,data:ywlarB/SG9jOJ9xW,iv:bgQlInnlPzxFzrYxXAlhQ22yGlKtJsvqeisP8NiVDhE=,tag:3N8rcraUh34IyPbHtWZsPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQzc4MSs3SGxDYnF1TmNW
            WFplNlVmU2VDRDhxVEJuZUJDOE00VFVtQUVjCkVwREIrSG1EWDByRjhtVjE1OWtj
            cmVQSnZ5QlhUR2w0REpvTk5CTXZZMUkKLS0tIEhobU9DZXo4cExNdHdXa2E4TXBu
            REZ5NWZma0NRR3BkaWxXNjFqUHBqbGcKM6cd/eZtadDnRwLdrpE8g655hB8wv0ZR
            1UV8bcH7pWaFuQ9A1E060jIX+Lipix//aSyr84kJozQGWDOVnIC5qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T02:46:51Z"
    mac: ENC[AES256_GCM,data:rEWRgyWqCP5ggQGAeKJBgiCZWsC3KeEvM1Pmn2+KYOLOoDR3X0rnt05fUaaniey26nS+rXoZqcr3xeOf09cGgBAZl/WTOVDS3l8+MiGvja9KI+vFEJr/2m7Q7wS/eDEx02+UKqZGt6RW4j6Ip0e82LztY9TfWB+OKKngwtVISng=,iv:yKKfo+pkNpVtPFU3krqzTGQBG7h1Ml8g3p2vTSjc7DY=,tag:Egvb3jDOG6Qib7thvMJ+cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
