"""
Configuration management for kubani-dev.

Provides a layered configuration system that allows developers to work
with different environments (local, dev, production) seamlessly.
"""

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

CONFIG_DIR_NAME = ".kubani-dev"
CONFIG_FILE_NAME = "config.yaml"

DEFAULT_CONFIG = """# Kubani Development Configuration
# Generated by kubani-dev init

# Cluster service endpoints
services:
  temporal:
    url: https://temporal.almckay.io
    namespace: kubani-dev  # Separate namespace for dev work
  
  redis:
    url: redis://redis.almckay.io:6379
    db: 1  # Use a different DB for dev
  
  vllm:
    url: https://vllm.almckay.io/v1
    model: qwen2.5-32b-instruct
  
  postgres:
    url: postgresql://postgres.almckay.io:5432/kubani_dev
  
  qdrant:
    url: https://qdrant.almckay.io
    collection_prefix: dev_
  
  kubernetes_mcp:
    url: https://kubernetes-mcp.almckay.io

# Development settings
dev:
  hot_reload: true
  auto_eval: true  # Run evals on every change
  eval_subset: smoke  # Which test suite to run automatically
  log_level: DEBUG

# Evaluation settings
evaluation:
  enabled_strategies:
    - automated
    - llm_as_judge
    - simulation
  
  llm_judge_model: gpt-4.1-mini  # Cheaper model for evals
  
  thresholds:
    task_success_rate: 0.85
    tool_selection_accuracy: 0.90
    step_utility: 0.75

# Observability
observability:
  trace_all: true
  metrics_port: 9090
  dashboard_port: 3000

# Test datasets
test_datasets:
  smoke:
    description: Quick smoke tests
    path: tests/datasets/smoke
  golden:
    description: Golden test cases
    path: tests/datasets/golden
  regression:
    description: Regression test suite
    path: tests/datasets/regression
"""


@dataclass
class ServiceConfig:
    """Configuration for a cluster service."""

    url: str
    namespace: str = ""
    db: int = 0
    model: str = ""
    collection_prefix: str = ""


@dataclass
class DevConfig:
    """Development settings."""

    hot_reload: bool = True
    auto_eval: bool = True
    eval_subset: str = "smoke"
    log_level: str = "INFO"


@dataclass
class EvaluationConfig:
    """Evaluation settings."""

    enabled_strategies: list[str] = field(
        default_factory=lambda: ["automated", "llm_as_judge", "simulation"]
    )
    llm_judge_model: str = "gpt-4.1-mini"
    thresholds: dict[str, float] = field(
        default_factory=lambda: {
            "task_success_rate": 0.85,
            "tool_selection_accuracy": 0.90,
            "step_utility": 0.75,
        }
    )


@dataclass
class ObservabilityConfig:
    """Observability settings."""

    trace_all: bool = True
    metrics_port: int = 9090
    dashboard_port: int = 3000


@dataclass
class KubaniDevConfig:
    """Complete kubani-dev configuration."""

    services: dict[str, ServiceConfig] = field(default_factory=dict)
    dev: DevConfig = field(default_factory=DevConfig)
    evaluation: EvaluationConfig = field(default_factory=EvaluationConfig)
    observability: ObservabilityConfig = field(default_factory=ObservabilityConfig)
    test_datasets: dict[str, dict] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "KubaniDevConfig":
        """Create config from dictionary."""
        services = {}
        for name, svc_data in data.get("services", {}).items():
            services[name] = ServiceConfig(
                url=svc_data.get("url", ""),
                namespace=svc_data.get("namespace", ""),
                db=svc_data.get("db", 0),
                model=svc_data.get("model", ""),
                collection_prefix=svc_data.get("collection_prefix", ""),
            )

        dev_data = data.get("dev", {})
        dev = DevConfig(
            hot_reload=dev_data.get("hot_reload", True),
            auto_eval=dev_data.get("auto_eval", True),
            eval_subset=dev_data.get("eval_subset", "smoke"),
            log_level=dev_data.get("log_level", "INFO"),
        )

        eval_data = data.get("evaluation", {})
        evaluation = EvaluationConfig(
            enabled_strategies=eval_data.get(
                "enabled_strategies", ["automated", "llm_as_judge", "simulation"]
            ),
            llm_judge_model=eval_data.get("llm_judge_model", "gpt-4.1-mini"),
            thresholds=eval_data.get(
                "thresholds",
                {
                    "task_success_rate": 0.85,
                    "tool_selection_accuracy": 0.90,
                    "step_utility": 0.75,
                },
            ),
        )

        obs_data = data.get("observability", {})
        observability = ObservabilityConfig(
            trace_all=obs_data.get("trace_all", True),
            metrics_port=obs_data.get("metrics_port", 9090),
            dashboard_port=obs_data.get("dashboard_port", 3000),
        )

        return cls(
            services=services,
            dev=dev,
            evaluation=evaluation,
            observability=observability,
            test_datasets=data.get("test_datasets", {}),
        )


def get_config_dir(project_root: Path) -> Path:
    """Get the configuration directory path."""
    return project_root / CONFIG_DIR_NAME


def get_config_file(project_root: Path) -> Path:
    """Get the configuration file path."""
    return get_config_dir(project_root) / CONFIG_FILE_NAME


def init_config(project_root: Path, force: bool = False) -> Path:
    """
    Initialize the kubani-dev configuration.

    Creates:
    - .kubani-dev/ directory
    - .kubani-dev/config.yaml with default settings
    - Local evaluation datasets directories

    Args:
        project_root: Project root directory
        force: Overwrite existing configuration

    Returns:
        Path to the created config file
    """
    config_dir = get_config_dir(project_root)
    config_file = get_config_file(project_root)

    # Create config directory
    config_dir.mkdir(parents=True, exist_ok=True)

    # Create config file
    if config_file.exists() and not force:
        logger.warning(f"Config already exists at {config_file}")
        return config_file

    config_file.write_text(DEFAULT_CONFIG)
    logger.info(f"Created config at {config_file}")

    # Create test dataset directories
    datasets_dir = project_root / "tests" / "datasets"
    for dataset in ["smoke", "golden", "regression"]:
        dataset_dir = datasets_dir / dataset
        dataset_dir.mkdir(parents=True, exist_ok=True)
        (dataset_dir / ".gitkeep").touch()

    # Create connection profiles directory
    profiles_dir = config_dir / "profiles"
    profiles_dir.mkdir(exist_ok=True)

    # Create local profile
    local_profile = profiles_dir / "local.yaml"
    local_profile.write_text(
        """# Local development profile
services:
  redis:
    url: redis://localhost:6379
    db: 0
  vllm:
    url: http://localhost:8000/v1
"""
    )

    logger.info("Initialized kubani-dev configuration")
    return config_file


def load_config(project_root: Path) -> KubaniDevConfig:
    """
    Load the kubani-dev configuration.

    Args:
        project_root: Project root directory

    Returns:
        KubaniDevConfig instance
    """
    config_file = get_config_file(project_root)

    if not config_file.exists():
        logger.warning("No config found, using defaults")
        return KubaniDevConfig()

    try:
        with open(config_file) as f:
            data = yaml.safe_load(f)
        return KubaniDevConfig.from_dict(data or {})
    except Exception as e:
        logger.error(f"Failed to load config: {e}")
        return KubaniDevConfig()


def save_config(project_root: Path, config: KubaniDevConfig) -> None:
    """
    Save the configuration to file.

    Args:
        project_root: Project root directory
        config: Configuration to save
    """
    config_file = get_config_file(project_root)
    config_dir = get_config_dir(project_root)

    config_dir.mkdir(parents=True, exist_ok=True)

    # Convert to dict for YAML
    data = {
        "services": {
            name: {
                "url": svc.url,
                "namespace": svc.namespace,
                "db": svc.db,
                "model": svc.model,
                "collection_prefix": svc.collection_prefix,
            }
            for name, svc in config.services.items()
        },
        "dev": {
            "hot_reload": config.dev.hot_reload,
            "auto_eval": config.dev.auto_eval,
            "eval_subset": config.dev.eval_subset,
            "log_level": config.dev.log_level,
        },
        "evaluation": {
            "enabled_strategies": config.evaluation.enabled_strategies,
            "llm_judge_model": config.evaluation.llm_judge_model,
            "thresholds": config.evaluation.thresholds,
        },
        "observability": {
            "trace_all": config.observability.trace_all,
            "metrics_port": config.observability.metrics_port,
            "dashboard_port": config.observability.dashboard_port,
        },
        "test_datasets": config.test_datasets,
    }

    with open(config_file, "w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)

    logger.info(f"Saved config to {config_file}")
