apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vietnam-trip
  namespace: trip-planner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - trip.almckay.io
      secretName: vietnam-trip-tls
  rules:
    - host: trip.almckay.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vietnam-trip
                port:
                  number: 80
