apiVersion: v1
kind: Secret
metadata:
    name: trip-planner-db
    namespace: trip-planner
type: Opaque
stringData:
    PGPASSWORD: ENC[AES256_GCM,data:4s/sLS64S79v8p2WBYkxwKJ3ipTtbhKI,iv:wtfZNjQ48A0a9hPNMOTLmB09aUddCDkznOE4chtKoX0=,tag:95GfzP0bqZwWcnx1ugTv0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSGpudWhwUVUyamZKMFFn
            bnd3S0d2OU5SWFZZdFZWWldWVkFBNGxCbTF3CkxzM21KUnVsQkJjMzc0eUxvM3Q0
            dUJlRU1PUWtsK0RHU0JCbUxzVW5XcnMKLS0tIGg4N3o0NE1RaitCcUtZUTgxSC9t
            QmZVa1RCR3ZxRGdjdFErdU4rZHlESFUK3UNmqmkwJVwdJymxdMbYCkMGvJJzOTM4
            hfSWzTAf+YWGp/z9SiKhuDkofU1W3iCcN7dVYlIFFE5C9CBtBT5Z2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T00:03:54Z"
    mac: ENC[AES256_GCM,data:lHnQgMzbkZTQGQCPESa1pyNCiUNByeWZPz4g+i15MDSZLmTbnTP7pQqVu/ekyNR5lwuvbPzhvjnGnk9+/FkXI6zJLDwDb4l7KRAB/uQ7kvfs+P1qFjna4oVX9fHOWs39oTNkfy+MdiYjoa4YiNQEs3HShGSl3uyfPQ0n1KZ4bis=,iv:AHzYytK8XijtL487jAwGpRzjPGaHzdB1v9VG5R6kmh0=,tag:E8s+lwZc2S4CfVOhiUUmCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
