apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbase-core
  namespace: starbase-system
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/x-mckay/starbase/web@sha256:4e97f206917bb72b4c001cb3c75822f4f642c105ef4700cc2722b1c3e3a1ff81
          imagePullPolicy: IfNotPresent
