apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbase-core
  namespace: starbase-system
  annotations:
    starbase.io/activation-state: authorized-rc4-runtime-rollback
    starbase.io/activation-stage: phase5-rc4-runtime-rollback
spec:
  template:
    metadata:
      annotations:
        starbase.io/activation-state: authorized-rc4-runtime-rollback
        starbase.io/activation-stage: phase5-rc4-runtime-rollback
    spec:
      containers:
        - name: core
          image: ghcr.io/x-mckay/starbase/core@sha256:61a0fe54fd5903f5afb9bbae254c794e590444611fdf089308b5a9f70e1e4054
        - name: web
          image: ghcr.io/x-mckay/starbase/web@sha256:ab5e5aa20e7c318f38bbfb8c20c739bfa10b5b4888ef152623367dbc24ed9baf
