apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-config
    namespace: monitoring
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:4021YROualtB7hiUh2JgUq1/V8pR8cI+rgShR28/0LZwG8Y8adCEHvut8pEDem6vIF11hlIdVDJDhYxynd5maVuCCsuHEX+vWlgCqQP0D7wauq0PS7aHb3m0D2252QlfN+TfuBuInXLuTgLJNLsZkepW9GdubxQl7qUdXs+y/X7zpjY8AjJrG+PXHF5vSDaipRQ2wnXEw8DpMT3BHz1S8b36d6JnhQSPqig6E6b3BN7brccEDBI42wr5cBTmob/OJOM468GwkhRtE77XM0kW6lg6lP/KjyBsRnkoII5zHd1q6Y3xb6OTwvRGMOO5UiGs4c5l9zS6woiht44LFx74McsbMUK3kcxUK4EXuMpK3mkRgsWvZ8LJ9oY+9I07vONzf8W3ygBDBDCfncCHpIebodvCgncfNqt77nKcwNEGJmJOr6zGBa7tTUvq0zvquoXwpQ7+/v+KWevOY1g0neUQDrXzlsE+Xc/fv7n5a+hSFOZT4ReJZSTsNgQxkchKY5AGK68kl1qqExxZrsF6ySiXgwQC7/XJy8/pPDj1XgnwZG4EoBd+4Gzmp61MfJmCNpxIBTnr4lnts+zuqshUM6/63P56w9w4G9zU9kg8PqXP28jMNiUqqdecsLF/Hc5lUa9CfXXFpFAVqKeUeDLAOSBYH9IRFhtI+8Hgzg6c64anNzZGfmURA2WHDnrOAGRgEwDU898kfRVMK87+A5V7/knbNjghtAhbJgab/XxdqjfEfN/xa8x7Ax/MAo1huPiiRpz99OD4xpk9q/ty0Z/no0RwEPOJndrVLfza/cd/gLdWoil4rS7/JVF0f4CymT1hNhl4otw+Ai9ue9Ay8TaxG1z7zRCEGHCX5lC1PdeFd8RIfz/EyLr3ysfu8AE8U5z4QLivnV3VhJLZENTwDkxtx1X9S2NDnw4tdGgtF0gGshnu4O8lL6XJL16VcNVV/4etDPFCTQ1ZD0V9agwi6qj4s5pzAGZ1ugDQhSFNnwrYgrmtFMTYgbujQcRu+/KVGwmK7L+xYLxYI2XNSlY5WPH8JifWS1m+sjmgY9sWgjOGN0SRDGUh7Zmuf7smQe5JpIB5Sq53ygPHFDjZtT9uzbt4eVMMC4tl14Re9vYh8yxfwX0=,iv:wnYm6xrFoGBdJdK7VgT3VQWELIBB8AW4AHCnssQHpD0=,tag:1+nnQPJ7n6CFPGn9vLRmkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVnZDUzB5bDNYelNuR2tu
            MlF2L0d0RjQwQ25tYTl2em0vYUduQm42Wm1BCnVNRnZmWUttQ2F6d2U4bU5xWndD
            TGlKdlVSQVNCdElndWhsVEprMkJPbU0KLS0tIExmZ01aa25hcHdqV3ZoYys2K2NO
            YnVHLzE2bTJaR2t4SmZDVnBVbmdDUHMKPMNCrZOPK/HBI/yZrsFe0IaHstwvGo7b
            Kyj5HVLGKs1Taj9KKXJ2yP0xktygAIfLi59K11flT8DSOywWQ3hm0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T12:13:37Z"
    mac: ENC[AES256_GCM,data:gxK1g4AdVltjQqmERPOk3M+cXHfK/xYo76KX7JSq2WsPtWqkoJJmuyDR1D7zyuqFR3ScADhejMzFCnKNVudMzCz1RW7WdUuJtI9Dat7N32D1ruKOE8qlWgKwc5P2wh49jzlcVckEUEjHN9J26vEraTh342PygWMe4olIxRg/SsA=,iv:ouPxBbo9BuL875v81FkP419vHmt+s4nziWDRPyUl/mM=,tag:UYeUqnX+c6XTMJykmq9BOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
