apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-config
    namespace: monitoring
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:AtkGmKppoDqGalv6grwCq9w24yjJV9NZPRKN19yzh2W6Pphi+lKdvR+kP7Zztqs+72bVm1iFey0tBGsEKIHomRRd+qM+1piUDi9SfuAfG0+1kyXd8VmKFDq4yneMsPZOankcBzZ15cUygrrWGzAd35Nvu7WEkwbJEDR/3tktbhWGwxsw8I3TaT31jKzrcuxHMq9kbUBMXVYN7hEq8MwAwHLu9UtXcgbr4IjwSq+FdqoynI81weUoWAaMUH4Ef6rgTbQQxa1V1AOjAnfILyRFmCCP4HhqNRhSXzfhMst1ac6pk5FPXw6kSpi44Sqye+NxKCqxdULECsZnv8dABLICs78sty5WR1HVi6Qu0NNDZo4J/za6yK//w9c5iOncy5JjsLU/3dGJeFPrMiMEnuVrkE9QQTqidRBjwvxNbVNJzaXxQtTJNvaQs3EHCD0pu3CYUvkImi62K5KWJfGII9vzbvNHmdhJPY6IrJHNlcqPadYllr86auJKKeVYMdKNjiW2lpK6fXHIOvnOPG7nxEfrv5xo30MGCOhMJTWsEmelAYSBsU8Q6gdII7PTD7ZuUb0sNcHBMwPDAo8v9wr7hHntN8PE5KcCqR8VHsKPUKyH65AMbtRC93LcBNswtKL4XkopSgqIq8zvA/GLGr9cZgQ2xUxfHtS17DGR40wPuKmYSWdZYKws/CGxb/bOsUj2L2GCbioNLX1eOmtVjiw53pR0+HydrrMwEgRT+Z+1uzW2Vr/o8FQMft1Mb7BU8h6GYvqYEqJQfBw11GP8mRfMtrSGN7RUQy2h8TLjtcwO30Q4a1t+5i3oZjJ2qLrquHUGJQd4GullluZn41vKQxrsSxST+oA7Cc0Brv+gpc24OoRKMC9S8mQ7d1+w+prquvmngCh0Rqfkk9BJXW1u56FYYL/JadqOuJJNECyEas0M4bxhmyw6O2cyTkgll2KubwiLNxoN7kR3/aCPDwSWRruiQDLZRIfW1cxhy6afrgguPcy212YF4bAybeJ7eJ2ZWenurPdA5K7gIGaRnJHJF9xhdfU9B/TElBTVV5ogqIaqGD1aBi19n7MFFwtki8d7Xt3lBcFsozIY5eCdHwNk3kV79bOwJhVK0rY6rfA/N7I=,iv:ZQJD9IsvSabtsF4W/4VtpRhznXBeBPAGtMAZwE+JuDI=,tag:cajk0odE6Ns+GRUFRkMxDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M0xKN0J5Qk44QU9LWnVm
            RzJVb29GTFJ2R1NxZXJ5WDF3YmZ6UTkyZzJnCnlTcUxQTkdCNlhpblRvSjNybUZ2
            NXR2cVM5K3BMN3RPMDZIdllJV2w5a3cKLS0tIG5MWGNFWW1vRjBDUW9LWnZLVWtw
            dFM3eUtsM2xDc0d0ODBCTmtzRkJSTDQKSB2SL33vbiRkKfK2TEdD7Y+h7KZCk3mX
            spRzhCG5qiftzG2UpKWDKFeLHeKr+F+/AmuG2RrTj9B3BQQWyCCaEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T11:32:08Z"
    mac: ENC[AES256_GCM,data:uNk0yBwX3x1I4kX7iLM+uWfD5JGi3DB7Y7gKKfgpl0TQGY3DnauPBdk+gX+MVEf3tH9oTs6vrwigTiBMABbPOs3e4mpXDNb6S2phNCVzpmk2L899uForWd4740FeoTS8qlpv1REnnOHaEC0jsL3ljdVkwB3//rvsFQw2Jz6L5Fo=,iv:yPG7bz3CXREXLtQkZ7xTHl7X4PCahL84ezxvDYSt9lY=,tag:LRUEfM62522f0A4ruscsew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
