apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth
    namespace: monitoring
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:I4zvlLN5JdO2ILkqpsWI/AOgCahgfnkxXboO1vrBa0vdUxhklSm+HphQ5AvkFHH6AQOCuHug6vRDCYwbfgZOiOvB8ayQtLq/5IbsMerTJZIk1nGcHyjUMOghgGSrQDvU97gRaiWnf5GdiZoo5RCuDOY00/Uu5+iPB48oAsBHMczO8UApH5VYZw+GjwRkQALtLxyH0Q==,iv:sbHij0263kiyp1XKBDdbO8fFEJ112EieRZFGkv7fp8o=,tag:Q4X3t6r6f2D6WVBAQsiYMw==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:usAsOcKT7t3oLkTcb7KrD7DN0U93m+e2Xx1QvuRygbg+LbK11lpXJjT1K87tPH8+HXV4qnX1FHMgySA+CFPCAqTXM5ObeA==,iv:2DLhtANST9spnTlc12IuWK/S5eSXrym0e8WRW7xRt/M=,tag:P3ILCPnQQbk6nRj24L8F1Q==,type:str]
    NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:D4e8JNC1GB4Yn86UZ0DaC45gszGpVFkox/IOSWy2kPY=,iv:U18/+eBIeChZVFX1d0gDDZ0YRO9JIvVfF+HFZiM9xwU=,tag:5RcKVgobnH1C6qzO915wyQ==,type:str]
    #ENC[AES256_GCM,data:tFnySBQ0IO5yC75FVdqEkne2MAY62U3yVow2nAybR94N0VHUghPVnz1kfTD5VC0/7Hyq69mcZZN2yNo9/xjKXu8=,iv:wOtLJDfuERrx1UXJgeMvRmQj4+SkCOWHpocCt5mCqdk=,tag:UJfhB6QIKsGdaIn6WlJMcg==,type:comment]
    al-password: ENC[AES256_GCM,data:Aw2yaOOUZHFIQtHIEYFysxYcjrvIJBi2,iv:RAXSZ8O5noEAStZmxhINBMa1wIeXG5wglNKoVPFyr90=,tag:gxC68KtYEHJRJWiuF7y2TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U1JUUGhuWExremdDT0dH
            bi9LREVweSsyczJEY0M4VVBPbVpoUXZzb0h3CkQrMDhvYXJhd3Z0bXFXRGo3YkMw
            OWdWclFxc1lteXNqaVpnQkJoaExFb2MKLS0tIExzS2FyN2p6TkJSSkRHOVZFWFBI
            NXA2ZGR0bE84QVhidGhiYXFmSFJuaTgKhIiOekSZd1yCXZJdMbEIA5XEEewwlJUM
            5pc3/Lp+n4N1AyW73MjGAVPNjicz5+U2ByXGVf42N0LIrE04XOoZIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T12:13:37Z"
    mac: ENC[AES256_GCM,data:75yh+GTx2XQypfSK5DFMDtGFcaLhm1PrHgQgyxdfIOQgAyI8T45UlLaNHrlwJdQSFguC+T3UwogiVkemWWA9nq5z8Smy8tf0g8KvqIOhVJjKJ93A49kFmDGjI9ZoXEieIJei2Mj/quq6g+Zf93Kc/Tq5dwbiDUbEniWip8pR+/M=,iv:aa3iAQ0c6SlebeA5Jx5TkliwQP75Ua8wHEjhjDXFzxs=,tag:XpRNBxGgYTgIm/bLjiyHfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
