apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-credentials
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:tqRe7tkxPw==,iv:ONhEJsgkKGBer3PVjXLR3sFpBC9ewdenG26YOubDOq0=,tag:qBgY60Tz34egIJfZQj4XcQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:uuAlkYWGbJ3lC4w4uRUMxYc2gGGilqkSHvNJRSeziE/KNId21Z5Yru2Q7yxvH5FRWM/1pWPM+zPlTh74F4iAHA9Wt2JzOuu2F0Z6YYyBoNlz16gdbZqkW9a0bjK+uTPg6yGUE17+v1BcGjlABVKNDh+bXdf2PhhCVf+pJAQw3UM=,iv:Lip3yNA4lZQOIWB6mmFcnFdQrlAa1cgia82Hj0izx1A=,tag:s9vnZKX2aMYcOQm1/svTOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmdNYVBXcGpxbFNheU4y
            djV2ekJTTWVCOFY5RER1M2V1T2pBWXpZVFZBCjgva0xCMmpZY05HRlN1dWpMelhU
            aGJVNFhpVmgwYzlZd2NvWkdQK2EyRjQKLS0tIDB4R3B3K0NSNlQ5bWR0NUFOTUdD
            bmNWbDJrVmZsR3J5U1lzbkw1N2FDbzAKZhSiHsi5bYilC8cMg+eEgC6O0DzLZ2Wg
            e/yMOf+JVoNRw0fqKcXHcNzlaYbGD+nWUCyGD0qmgqSf8odke1RTEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T20:34:51Z"
    mac: ENC[AES256_GCM,data:K2OnGdCF4n8/6o89iMKU4gMcZFFatFOKurTl68QLWHyFlHe9NTXp7nRr3Znl49j7UuHktJ2j/6clVNOLnTn7pS3Mnov+rMWFtH7TGwmVaazZZkfufV4y0bPeXnonqgPJV/h4/h9GxgVvg4bXVtFjUgJ6iY92xPfvZsP4Fm41AO4=,iv:Vhc9G2zJ6NDs1Mp++yfJqh+L/Dm21FW5T5aeg3h71Is=,tag:6FigGOzmAG9+iR1e/06w8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
