apiVersion: v1
kind: Secret
metadata:
    name: qdrant-metrics-credentials
    namespace: monitoring
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:nusAcf89Rg95ME5wVK79g4IHcdTdtZ6n8OnZ5g4SdASkHysAQHounQ==,iv:XlJkvqfblV9wRjj4TtdZSPh/s+PIjZucrxRrub6HOcA=,tag:pZdJxeFV/zb5ODy6Unj7PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ0dVamVaY0FrdmFFVWJ1
            cnp0RGxhOFZQaFBxRExmVWF1emtGMldYTzFZClJaTkhIT1dqZXQyRjduWGpLd2hu
            c0pReDZnanlPbGVxSG9jc09lL2VWWFUKLS0tIFBwN2ZOc0c1VUZ1ZjlycFNKTnVn
            SGc1Vks1SEhuTWpDTDNYUzFncW9qTXcKINGxVpWbrgjMHjDvysdA46tp7EKlag4G
            ago6J6CN73oIcbgbd99J5W8uW2jCxwgb0wPtYiWNGEZ9wKtLnJCOvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T11:31:56Z"
    mac: ENC[AES256_GCM,data:3iVpVtUJR51sgVYjBel9QsUC1guZHk54Z5oRm+kuiNfEPn7wyoUd66CwwXRfh8uDHPWEr+tITlO2puidFV20cjX0Uhptjr+Bl5oMStExgBLOuZEUSLJ19HbNfx04o45QS4yVbB2Gq0d7onM9s4gpGeBRqNi+dM9lZZEb+sDV5C8=,iv:zsUWywEL41wq4kFeGHImEkADZH+KI1I6ECVT5HiZNX0=,tag:2fRfy/5E3TRZSlmtzPy9Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
