"""
Explorer Agent - Skill learning and gap identification.

The Explorer agent implements the Voyager-inspired "curriculum" pattern:
1. Analyzes incidents that couldn't be matched to skills
2. Clusters similar unmatched incidents
3. Proposes new skills based on patterns
4. Submits skills for human approval
5. Requests new MCP servers when capabilities are missing

This enables continuous improvement of the skill library.
"""

import logging
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Any

from pydantic import BaseModel, Field

from core_agents import create_agent
from core_agents.approvals import ApprovalRequest, ApprovalStatus, get_discord_approver
from core_agents.events import EventBus, EventType, get_event_bus
from core_agents.observability import record_event_published
from core_agents.skills import (
    MCPToolReference,
    Skill,
    SkillAction,
    SkillCategory,
    SkillDomain,
    SkillLibrary,
    get_skill_library,
)

logger = logging.getLogger(__name__)


@dataclass
class UnmatchedIncident:
    """An incident that had no matching skill."""

    timestamp: datetime
    reason: str
    message: str
    namespace: str
    resource_name: str
    resource_kind: str
    original_event: dict[str, Any] = field(default_factory=dict)


@dataclass
class IncidentCluster:
    """A group of similar unmatched incidents."""

    pattern: str  # Common pattern description
    incidents: list[UnmatchedIncident]
    frequency: int  # How often this pattern occurs

    @property
    def sample_incident(self) -> UnmatchedIncident | None:
        """Get a representative incident."""
        return self.incidents[0] if self.incidents else None


class SkillProposal(BaseModel):
    """A proposed new skill generated by the Explorer."""

    skill: Skill
    based_on_incidents: int = Field(description="Number of incidents this would address")
    requires_mcp_server: str | None = Field(
        default=None,
        description="MCP server needed but not available",
    )
    confidence_reason: str = Field(description="Why this skill should work")


class ExplorerAgent:
    """
    Proposes new skills based on unmatched incident patterns.

    The Explorer analyzes recent incidents that couldn't be handled,
    identifies patterns, and proposes new skills for human approval.
    """

    def __init__(
        self,
        skill_library: SkillLibrary | None = None,
        event_bus: EventBus | None = None,
        source_name: str = "k8s-explorer",
        min_cluster_size: int = 3,
        lookback_days: int = 7,
    ):
        """
        Initialize the Explorer agent.

        Args:
            skill_library: Skill library for storage
            event_bus: Event bus for subscribing/publishing
            source_name: Source identifier for events
            min_cluster_size: Minimum incidents to form a cluster
            lookback_days: Days to look back for incidents
        """
        self._skill_library = skill_library
        self._event_bus = event_bus
        self.source_name = source_name
        self.min_cluster_size = min_cluster_size
        self.lookback_days = lookback_days
        self._proposal_agent = None
        self._unmatched_incidents: list[UnmatchedIncident] = []

    async def _ensure_initialized(self) -> None:
        """Lazy initialization of dependencies."""
        if self._skill_library is None:
            self._skill_library = await get_skill_library()
        if self._event_bus is None:
            self._event_bus = await get_event_bus()

    def _get_proposal_agent(self):
        """Get or create the LLM agent for skill proposals."""
        if self._proposal_agent is None:
            try:
                self._proposal_agent = create_agent(
                    name="skill_proposer",
                    system_prompt=PROPOSER_PROMPT,
                    tools=[],
                )
            except Exception as e:
                logger.warning(f"Could not create proposal agent: {e}")
        return self._proposal_agent

    async def start(self) -> None:
        """Start listening for unmatched incidents."""
        await self._ensure_initialized()

        logger.info("Explorer starting, subscribing to remediation events")

        # Subscribe to failed remediations (no matching skills)
        async for event in self._event_bus.subscribe(
            EventType.K8S_REMEDIATION_FAILED,
            consumer_group="k8s-explorer",
            consumer_name=self.source_name,
        ):
            payload = event.payload
            if (
                payload.get("escalated")
                and "no matching skill" in payload.get("reason", "").lower()
            ):
                await self._record_unmatched(event)

    async def _record_unmatched(self, event: Any) -> None:
        """Record an unmatched incident for later analysis."""
        payload = event.payload
        resource = payload.get("resource", "unknown")
        parts = resource.split("/", 1)
        kind = parts[0] if len(parts) > 1 else "Pod"
        name = parts[1] if len(parts) > 1 else resource

        incident = UnmatchedIncident(
            timestamp=datetime.now(UTC),
            reason=payload.get("reason", "Unknown"),
            message=payload.get("message", ""),
            namespace=payload.get("namespace", "default"),
            resource_name=name,
            resource_kind=kind,
            original_event=payload,
        )

        self._unmatched_incidents.append(incident)

        # Prune old incidents
        cutoff = datetime.now(UTC) - timedelta(days=self.lookback_days)
        self._unmatched_incidents = [i for i in self._unmatched_incidents if i.timestamp > cutoff]

        logger.info(f"Recorded unmatched incident: {incident.reason}")

    async def analyze_and_propose(self) -> list[SkillProposal]:
        """
        Analyze unmatched incidents and propose new skills.

        Returns:
            List of skill proposals based on incident patterns
        """
        await self._ensure_initialized()

        # Cluster similar incidents
        clusters = self._cluster_incidents()

        if not clusters:
            logger.info("No incident clusters found for skill proposals")
            return []

        proposals = []
        for cluster in clusters:
            try:
                proposal = await self._generate_proposal(cluster)
                if proposal:
                    proposals.append(proposal)
            except Exception as e:
                logger.error(f"Failed to generate proposal for cluster: {e}")

        return proposals

    def _cluster_incidents(self) -> list[IncidentCluster]:
        """Group similar incidents into clusters."""
        # Simple clustering by reason
        reason_groups: dict[str, list[UnmatchedIncident]] = {}

        for incident in self._unmatched_incidents:
            # Normalize the reason for grouping
            key = self._normalize_reason(incident.reason)
            if key not in reason_groups:
                reason_groups[key] = []
            reason_groups[key].append(incident)

        clusters = []
        for pattern, incidents in reason_groups.items():
            if len(incidents) >= self.min_cluster_size:
                clusters.append(
                    IncidentCluster(
                        pattern=pattern,
                        incidents=incidents,
                        frequency=len(incidents),
                    )
                )

        # Sort by frequency (most common first)
        clusters.sort(key=lambda c: c.frequency, reverse=True)

        return clusters

    def _normalize_reason(self, reason: str) -> str:
        """Normalize a reason string for clustering."""
        # Remove dynamic parts (numbers, timestamps, etc.)
        import re

        normalized = re.sub(r"\d+", "N", reason)
        normalized = re.sub(r"[a-f0-9]{8,}", "HASH", normalized, flags=re.IGNORECASE)
        return normalized.strip()

    async def _generate_proposal(self, cluster: IncidentCluster) -> SkillProposal | None:
        """Generate a skill proposal from an incident cluster."""
        sample = cluster.sample_incident
        if not sample:
            return None

        # Try LLM-based proposal first
        agent = self._get_proposal_agent()
        if agent:
            try:
                return await self._llm_propose(cluster)
            except Exception as e:
                logger.warning(f"LLM proposal failed, using template: {e}")

        # Fall back to template-based proposal
        return self._template_propose(cluster)

    async def _llm_propose(self, cluster: IncidentCluster) -> SkillProposal:
        """Use LLM to generate a skill proposal."""
        incidents_text = "\n".join(
            f"- {i.reason}: {i.message} ({i.resource_kind}/{i.resource_name})"
            for i in cluster.incidents[:5]  # Limit context size
        )

        prompt = f"""
        Analyze these similar Kubernetes incidents and propose a skill to handle them.

        PATTERN: {cluster.pattern}
        FREQUENCY: {cluster.frequency} occurrences

        SAMPLE INCIDENTS:
        {incidents_text}

        Available MCP tools (kubernetes-mcp-server):
        - pods_get: Get pod details
        - pods_delete: Delete a pod (triggers recreation)
        - pods_log: Get pod logs
        - pods_exec: Execute command in pod
        - events_list: List cluster events
        - resources_get: Get any Kubernetes resource
        - resources_scale: Scale deployments/statefulsets

        Propose a skill with:
        1. SKILL_ID: A unique identifier (e.g., k8s-handle-oom)
        2. NAME: Human readable name
        3. DESCRIPTION: What this skill does
        4. PRECONDITIONS: When this skill should apply (list)
        5. ACTIONS: Which MCP tools to call (list with params)
        6. SUCCESS_CRITERIA: How to verify success (list)
        7. FAILURE_HANDLING: What to do if it fails
        8. REQUIRES_APPROVAL: true/false
        """

        result = str(self._proposal_agent(prompt))
        return self._parse_proposal(result, cluster)

    def _parse_proposal(self, text: str, cluster: IncidentCluster) -> SkillProposal:
        """Parse LLM proposal into a SkillProposal."""
        import re

        # Extract fields using simple regex
        def extract(pattern: str, default: str = "") -> str:
            match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
            return match.group(1).strip() if match else default

        def extract_list(pattern: str) -> list[str]:
            match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
            if not match:
                return []
            items = match.group(1).strip()
            return [line.strip().lstrip("-•") for line in items.split("\n") if line.strip()]

        skill_id = extract(
            r"SKILL_ID:\s*([^\n]+)", f"k8s-handle-{cluster.pattern[:20].lower().replace(' ', '-')}"
        )
        name = extract(r"NAME:\s*([^\n]+)", f"Handle {cluster.pattern}")
        description = extract(
            r"DESCRIPTION:\s*(.+?)(?:PRECONDITIONS|$)", f"Handle {cluster.pattern} issues"
        )
        preconditions = extract_list(r"PRECONDITIONS:\s*(.+?)(?:ACTIONS|$)")
        success_criteria = extract_list(r"SUCCESS_CRITERIA:\s*(.+?)(?:FAILURE_HANDLING|$)")
        failure_handling = extract(
            r"FAILURE_HANDLING:\s*(.+?)(?:REQUIRES_APPROVAL|$)", "Escalate to human"
        )
        requires_approval = "true" in extract(r"REQUIRES_APPROVAL:\s*([^\n]+)", "false").lower()

        # Build actions from text (simplified)
        actions = [
            SkillAction(
                description="Investigate the issue",
                mcp_tool=MCPToolReference(
                    server="kubernetes-mcp-server",
                    tool="events_list",
                    params={"namespace": "$namespace"},
                ),
            ),
        ]

        skill = Skill(
            id=skill_id.replace(" ", "-"),
            name=name,
            domain=SkillDomain.K8S,
            category=SkillCategory.REMEDIATION,
            description=description[:500],
            preconditions=preconditions or [f"Event reason is {cluster.pattern}"],
            actions=actions,
            success_criteria=success_criteria or ["Issue is resolved"],
            failure_handling=failure_handling,
            requires_approval=requires_approval,
            confidence=0.3,  # Start with low confidence
        )

        return SkillProposal(
            skill=skill,
            based_on_incidents=cluster.frequency,
            confidence_reason=f"Based on {cluster.frequency} similar incidents",
        )

    def _template_propose(self, cluster: IncidentCluster) -> SkillProposal:
        """Generate a template-based skill proposal."""
        sample = cluster.sample_incident
        pattern_id = cluster.pattern[:30].lower().replace(" ", "-").replace("_", "-")

        skill = Skill(
            id=f"k8s-handle-{pattern_id}",
            name=f"Handle {cluster.pattern}",
            domain=SkillDomain.K8S,
            category=SkillCategory.REMEDIATION,
            description=f"Automatically handle incidents with pattern: {cluster.pattern}",
            preconditions=[
                f"Event reason matches: {cluster.pattern}",
                f"Resource kind is: {sample.resource_kind}" if sample else "Any resource",
            ],
            actions=[
                SkillAction(
                    description="Get detailed events",
                    mcp_tool=MCPToolReference(
                        server="kubernetes-mcp-server",
                        tool="events_list",
                        params={"namespace": "$namespace"},
                    ),
                ),
                SkillAction(
                    description="Get resource logs",
                    mcp_tool=MCPToolReference(
                        server="kubernetes-mcp-server",
                        tool="pods_log",
                        params={"name": "$pod_name", "namespace": "$namespace"},
                    ),
                ),
            ],
            success_criteria=["Issue is resolved", "No recurrence within 5 minutes"],
            failure_handling="Escalate to human operator",
            requires_approval=True,  # Be safe with auto-generated skills
            confidence=0.2,
        )

        return SkillProposal(
            skill=skill,
            based_on_incidents=cluster.frequency,
            confidence_reason=f"Template-based proposal from {cluster.frequency} incidents",
        )

    async def submit_for_approval(self, proposal: SkillProposal) -> bool:
        """
        Submit a skill proposal for human approval via Discord.

        Args:
            proposal: The skill proposal to submit

        Returns:
            True if approved, False otherwise
        """
        try:
            approver = get_discord_approver()
        except ValueError:
            logger.warning("Discord approver not configured, cannot submit proposal")
            return False

        skill = proposal.skill

        # Format skill as readable message
        skill_description = f"""
**New Skill Proposal: {skill.name}**
ID: `{skill.id}`
Domain: {skill.domain.value}
Category: {skill.category.value}

**Description:**
{skill.description}

**Preconditions:**
{chr(10).join(f"• {p}" for p in skill.preconditions)}

**Actions:**
{chr(10).join(f"• {a.description} → {a.mcp_tool.server}:{a.mcp_tool.tool}" for a in skill.actions)}

**Success Criteria:**
{chr(10).join(f"• {c}" for c in skill.success_criteria)}

**Failure Handling:**
{skill.failure_handling}

---
Based on: {proposal.based_on_incidents} similar incidents
Reason: {proposal.confidence_reason}
"""

        request = ApprovalRequest(
            action="add_skill",
            resource=skill.id,
            reason=skill_description,
            skill_id=skill.id,
            agent=self.source_name,
            context={"proposal": proposal.model_dump()},
        )

        result = await approver.request_approval(request)

        if result.status == ApprovalStatus.APPROVED:
            # Add skill to library
            await self._skill_library.add(skill)

            # Emit event
            await self._event_bus.publish(
                event_type=EventType.AGENT_SKILL_LEARNED,
                payload={
                    "skill_id": skill.id,
                    "skill_name": skill.name,
                    "based_on_incidents": proposal.based_on_incidents,
                    "approved_by": result.responder,
                },
                source=self.source_name,
            )

            record_event_published(
                event_type=EventType.AGENT_SKILL_LEARNED.value,
                source=self.source_name,
            )

            logger.info(f"Skill {skill.id} approved and added to library")
            return True

        logger.info(f"Skill {skill.id} was not approved: {result.status}")
        return False

    async def request_mcp_server(self, server: str, reason: str, affected_incidents: int) -> None:
        """
        Request deployment of a new MCP server.

        Emits an event and posts to Discord for visibility.
        """
        await self._ensure_initialized()

        await self._event_bus.publish(
            event_type=EventType.SYSTEM_MCP_SERVER_REQUESTED,
            payload={
                "server": server,
                "reason": reason,
                "requested_by": self.source_name,
                "priority": "medium" if affected_incidents < 10 else "high",
                "affected_incidents": affected_incidents,
            },
            source=self.source_name,
        )

        record_event_published(
            event_type=EventType.SYSTEM_MCP_SERVER_REQUESTED.value,
            source=self.source_name,
        )

        logger.info(f"Requested MCP server: {server} (reason: {reason})")


# Proposer agent system prompt
PROPOSER_PROMPT = """You are a Kubernetes skill designer.

Your job is to analyze incident patterns and propose skills that can automatically handle them.

When proposing a skill:
1. Be specific about preconditions - when exactly should this skill trigger?
2. Use only available MCP tools - don't invent new ones
3. Include verification - how do we know it worked?
4. Be conservative - require approval for dangerous actions
5. Start with low confidence - skills prove themselves over time

Remember: Skills are KNOWLEDGE about how to use MCP tools, not executable code.
"""


async def run_explorer_cycle() -> list[SkillProposal]:
    """
    Run one exploration cycle.

    Analyzes unmatched incidents and generates proposals.
    """
    explorer = ExplorerAgent()
    await explorer._ensure_initialized()
    return await explorer.analyze_and_propose()
