apiVersion: v1
kind: Secret
metadata:
    name: kubani-ui-config
    namespace: kubani-ui
type: Opaque
stringData:
    redis-url: ENC[AES256_GCM,data:JEz2EMwaZNVNFkKzDnvMaP97u59zEupX1pQPikUGm3s6R5pZG+Kj+XhqTrUlmx3/4qcUrsFmqM1l7RMfxOXnVPekqEXdlUXkXvf1ZkwRm/E5Oc1WTBGgfAZ34p1kkMM=,iv:oE/XgpkIsbdI8raz92tbupTzHoWA7J/pnt3uJSPByzk=,tag:JbQyaQmyMsneL1lrtHNA3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2K0ljWDZtNnhOVjhzQlg0
            dVRlR0x0V0E0cWRsRUZxcXYvaVZsNkM3NzM4ClpOVlhrSkhmakNGeHdHSTd5dXRm
            bjdkZ2VOcnIxMWtma05oOStIcWNLSFkKLS0tIE0xN2xVNkVIbXgwdnBkdzNjWFdx
            YnVOUEJiZE5KWjBONXpqMkE4YnBoVGsKAu9LQ98feLOQgJ8U1Q6mcVzAoGJvR9nB
            GP/LRTpQWrjhUZo4QVdIrVPL54ulgXrd8ErY0aj66lPNMCqHSKja7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T04:30:41Z"
    mac: ENC[AES256_GCM,data:CsdqZiyP4osAzCRvn5rk3n7J3YaFCf8P6AYzhRBXyUCRvMcpkQZV0REpK+9vvJR516Bf335s1DPS28zUl2vuLcI5NwWc5vFHUXYkZQSxhd+2BksNQcpGZSRF3I4z0IQqcaTrJrLe+5gJYsT+5vooKEkYB9vW7cQHik10qgr96gw=,iv:FYidpiF8mL0QfhYI0S74m8W/FalJEzOkys5YFGmErzw=,tag:dt/NJw+maBQuW+A+KfYxCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
