apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup
  namespace: database
  labels:
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/component: recovery
automountServiceAccountToken: false
