apiVersion: v1
kind: Secret
metadata:
    name: backup-agent-secrets
    namespace: ai-agents
    labels:
        app.kubernetes.io/name: backup-agent
        app.kubernetes.io/component: ai-agent
type: Opaque
stringData:
    discord-webhook-url: ENC[AES256_GCM,data:T922Jx9+gffLo52l2IUTrx04BGWwX8ckZxU7nNgPMsv28pin0fw3CJ/hKEPe0QFAT47V3V+5MDnyBOcwB1p+1Zpyju4FW+vL/6YIrtTI7HvtQ/pmO71GzDln0LRDAKMf6A+oGcoEROCeeFeirlcZS8cpEpQu6YsvzwEFag==,iv:HFSvzlTA3eWWdZXruEKOxd9Us3HlMOheMZ5cHjctsdw=,tag:nVx9/OhIZrfPTqdh+OI8Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sph0zya56hvk004jcel0te9jk3yynx6zyq5pv0hgrs2dm6wszgssne3v8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdnUzbkxiZEtCbGkvWEtQ
            RmY0NDkyaW1XT3duQ3NaVTVNcXM2Y0tDZkUwCmxpUXNNc1pXTllaVEJYeDN2dkE4
            bXNzQWVXbjlrMGk0YW81SWJZa2ZROTgKLS0tIGpWTmo2UmdXSldOem9EVXIwV3dC
            UlpJNEVjQmk3Y3lwWjZ2U0VPaGkyUmsKPRRvZevl2T3lQC/bOIYKas7klBE+rKth
            DUZQRQ+/qjSiN5QMcJzqiBs7Tdbxo4pisHdH71hYGQFj3cNeykHOBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T14:53:21Z"
    mac: ENC[AES256_GCM,data:0OK+UGNzFlYr1StLHCnO0JT+K2V4BNFi1h6LN79l79e/hG1hoHt07cz5PbohaBysGpbKqMt539A8PYp7HAWB8Cac/nQlTzU201K6IMxtb0eA0b6mYSBl68fOg/w0r70RvYrASKMU6zEz2iiQF0inPIcA2T0DwO/7JseKM03YHDg=,iv:jAaCn+Gati2/F+A3pol97md2NjhkCdN5M39M+hf8LYQ=,tag:IqfWIlub8t5w+OhlR6sJPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
