apiVersion: v1
kind: Namespace
metadata:
  name: smb-csi-driver
  labels:
    app.kubernetes.io/name: smb-csi-driver
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.34
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.34
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.34
