apiVersion: v1
kind: Secret
metadata:
    name: k8s-monitor-memory-credentials
    namespace: ai-agents
type: Opaque
stringData:
    pg-host: ENC[AES256_GCM,data:9Mkh6P1EQ0/k41NhqGwUPSdywTQR3E2rsC8rQvaFNb8ALyJTig==,iv:vcPfpQXKjQ9YvWS+Y1GzYYJiULqp4P10N8RtVuFXOOY=,tag:Xorn6TeuGXfdUHTqtx6/qw==,type:str]
    pg-user: ENC[AES256_GCM,data:umNIv3zlf1RIYHk=,iv:iqvd25U4iw8MwxlNSRTxglWm+qHf2OQaV2X/WSj6qWQ=,tag:8VR0CrCXmMNPX95NxvPucg==,type:str]
    pg-password: ENC[AES256_GCM,data:tqiTupHUEqaLeUn0RjWOLzJ7k1v7cvl3nxgXTAI=,iv:grZjkGKlB0A86jICCj7XjRfu1LvzTZj4hMWA8eDPKuc=,tag:OKRDKOqe68Uzwe0HBAthkA==,type:str]
    pg-database: ENC[AES256_GCM,data:nahq9m7sDakowd5ECkQHGGC/,iv:Dcs19CAMA3k9Z500xx4ZB7PlxyZPcJmZtKKpUMt0gvE=,tag:qQ0CltyCt+dZc0cqKvTPHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Vkl2WklRTjFKdGcvQ0Vx
            dVZNZDdlZWkrUENzSVpzT0x3UVJXWVVJcUFZCnV2RHVNbUJSYUJ5SmdaMnVSbHQy
            N0hyQ1JuaGQ1NjdnQkxZVVJxSzhOdGcKLS0tIG9KdmkycnFzKzRNSUliZk1kOGJD
            a21Jak9ydnNYNjdaTDhxbEZyUjZMUk0KCmOrNh7cvTJhOVSzfw2dgikAxCfb7f+j
            52qWINmL//82XzbBmxRqX8TvPYiBODcUBmMaTvbSN1m37sQrFPtkvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T23:04:00Z"
    mac: ENC[AES256_GCM,data:plNxown7O4wHU6NTdKs+BEE3gyRS7FAVzTPBzCj/tvMtw0arxENaaP2tLips6n2MfbGJdReui7Xcy9RMWyYM5pAqZRhFhmsCVq/VarXfAhUQxvCb8S1DImEPi5b/VKq3RV45WrSUpW3j/1aD1N7Fdx9/r9vnK8cb1xhy1ARuYAg=,iv:wlsS2Aen531fpIkK0pWIKnx3RfWFWQ6JOkvu7TI/7Fc=,tag:N9E4CbLcGHACExAeqwjLMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
