apiVersion: v1
kind: Secret
metadata:
    name: qdrant-api-key
    namespace: ai-agents
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:zw75ReAPhmJnbe4oOeouTn00cRTHN+s=,iv:5HteaWFcoYX4dnLjEWdWK784BGgT/xH/j/YZrZx+70E=,tag:xZ78MlJT1anC/I4nqR5kkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZzF5bEVaUHYzRXRRbDdm
            UjJBTWFDNTA0TWFHcXgzeU80cW9NZWJ6c1E0CmVadW51TTgwMU5YOGFKZ21sS2ZR
            M29ETUpiWTJMcThSRVBNTWYrQWZCRUkKLS0tIE81eHBYQURrajBhYWZPcU1DR0Q3
            a2dmTnNKNkpjNmVMWGlYZjZHWUpyY2sKHuG5pZAlY9MEu5K6vBxPfR4KVstxt+04
            hLnjwkhp6AWlBB3NpHu3vehnPHPYUsj6GMFrp2dbcNxJZZKsFJAZyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T04:08:23Z"
    mac: ENC[AES256_GCM,data:Rcd7IEULEXBx40aiQ1eeyKzqmAABHL+Pq1oBlx5CFyNP9PVEkNiDIuyLDh4vYS4bqPzG60+cJJhF5Jv0ZkUfLDEfv3KgXadPBoFCSYoXQ0SLEwp5AkiKMnSFf0wVG7vlii5lK49eXpRZFppB70PAIH0wmGdEkxkjcU4LnOjqVtY=,iv:2hiCPdyGGWfLvSXvl2lYHyQO1TAt0mZUokdjpsrgxt4=,tag:29EuRCywa9szp1epzdpDXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
