apiVersion: v1
kind: Secret
metadata:
    name: k8s-monitor-secrets
    namespace: ai-agents
    labels:
        app.kubernetes.io/name: k8s-monitor
        app.kubernetes.io/component: ai-agent
type: Opaque
stringData:
    discord-webhook-url: ENC[AES256_GCM,data:bXxkI6UP6vsZa37+i2UPLcR5trM9+eO3m9cjB4X9kw8Eq3LwbUwCcYij1v1tI1wJn4nZ5XrBg9rGkX9iDqnsJAAIIh0y15lr3fQSADrdpY0WgTG2m+/60EegK65XG56jv99+7dMhebOCXEIzvFSMmkdyUktn76B1hrfHYg==,iv:Qn0uJhQFKC5yxFh+u6lVH6bxAVk1eb39zTpzCi1LFts=,tag:7M6vUqSwJPX4pS39KFEd+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sph0zya56hvk004jcel0te9jk3yynx6zyq5pv0hgrs2dm6wszgssne3v8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeHV0NVIwVHA0b2dqcXJE
            TGI1NmcwL2JPelRxcFY5MjU0OE9XL1dKcDJFCmtidkRjdGUreTRXOFY0RXlySXZi
            ZjV1RlhTOE80RUJSemd4VHFtWDJMWFEKLS0tIFNpYVFIeE5ZNDd6Rk14K2pBelpy
            Y09hQXlPcGNQUEJkb3BZWStpdUt3ckUK0gxhbBfST9hO2/dqnS8zcTJve61ctc2U
            9GxZb5cZdZ3eOztZnU6CT0s0i7iqchPIF+QXu2VqAKR4GSgdbF2oiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T00:04:19Z"
    mac: ENC[AES256_GCM,data:raN4YMqEuOVVXXHm/xxASsQ8mMxiRRY+/PcVHt4/JHd1UbMnUaRAsjx5IxqE5lJGOpjaUeaXYcI2FJoSay2fSg7jgRVPj/njg/pxMhY0qJujk37OBkafD6G5w9EfehANahhfsRZFf0rjMWj+0c5bsa+tOIhq26C1KXfEd7xl3KQ=,iv:G53ddgGOF1rQ+zAKnERY+NkyhcJoYbSNZVpWIrraA44=,tag:9mSsCurAh+KtoeACuoMrrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
