---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: falkordb-resp
  namespace: database
spec:
  entryPoints:
    - falkordb
  routes:
    - match: HostSNI(`*`)
      services:
        - name: falkordb
          port: 6379
