apiVersion: v1
kind: Secret
metadata:
    name: falkordb-credentials
    namespace: database
    labels:
        app.kubernetes.io/name: falkordb
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:DDzAG0m5wmCMYIuRAJ2m8XLBpx/x9LBkzv1d6LunA5pMghrjFxTurg==,iv:Pgcav/eOup6PdSRuqRMgRxeUEwJvK/nNoYMP0gCG84g=,tag:8QLnA3rf8oO8h7omEuKxxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMmxBd3o1RC8waW1TQTRm
            ZU1IRm8yNTVvcjZjZ21JRUM5VFpuZzVIckFBClVqYllJekxMKzRLVExRQ2V2VHJJ
            RXZpcWJ5MVVyNE5CbzVKMmRwTHlpbTAKLS0tIGNOUzlsbitnV3RFTWk0Y2JoZUY1
            R2FWOW9yN0VGY0pZSnBleWVnVmVIYXMKRnMSM/gqNfmHt9r088sGw7RyAi0x1LWR
            AyxyAqrzlx7Dv1GjQ2vWgq2PXnm8U8jiDVn980FF5vEJEkHe4qgwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T15:37:10Z"
    mac: ENC[AES256_GCM,data:MwOVdM1AehVhSDQMPUNXheGgwKbRpCrRmzsOkNh9MyFlKD4FY8XghxIzO1WaE0vZNRzxT5cpJQbr+IMMYA+hZprYyWKt5tWFCuYY3wk/v5IRQ+9zsUVNJRaTojr6oVs5UpArNyYOx+IfycPE7Xsgc08+6GMTz4s9BximBQAR+K4=,iv:2/Cy8PX9iZKjE5IoDAP0b4jroQkTHmMdjeWLHjevAVI=,tag:ZmXxw55Fk/lp8wZih0nq3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
