apiVersion: v1
kind: Service
metadata:
  name: falkordb
  namespace: database
  labels:
    app.kubernetes.io/name: falkordb
spec:
  type: ClusterIP
  ports:
    - name: resp
      port: 6379
      targetPort: resp
      protocol: TCP
    - name: browser
      port: 3000
      targetPort: browser
      protocol: TCP
  selector:
    app.kubernetes.io/name: falkordb
