---
mirrors:
  "registry.almckay.io":
    endpoint:
      - "http://registry.registry.svc.cluster.local:5000"
  "registry.registry.svc.cluster.local:5000":
    endpoint:
      - "http://registry.registry.svc.cluster.local:5000"
