apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: weave-gitops
type: Opaque
stringData:
    clientID: ENC[AES256_GCM,data:bznGLhnj43PuyeZ4,iv:33mX87RpeieuvmQp7Fy5CItm6MB6ZGKvMihQhbY6xpA=,tag:ikEUaz4IvX/Nv1LkFWY2EQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:ziiZ0HDWIBkQOmw6VtBukXF8ofguhasD1e+DJk2GFFXgv9U8PRHdFMX0MRaGg3teEDbMF9LebxNnHtDGijnfxuW6xzDtpx6bBY0kr6YbmBFE/hi4AoqjPjneIuOj1oQj4dczmQW/Tu8ee0D3FL6y1/OoXYWyb7MSdMrkAsV36CI=,iv:TzWSZl4cUbSwomqBit5tbUjeb2320APlqb0dw5oYQro=,tag:qXgR+ImAS3b9ea+c1hy/HA==,type:str]
    issuerURL: ENC[AES256_GCM,data:Oef8T71DpaVvUrWEsXrQXqHNQneH3/3oADIFzq2fBC6xlqD72VApelD++O8VvF5cBnqh,iv:fbIfS4nDLEBARI0mtN4XbM6O0CybvR91S/clvUh9S4k=,tag:XlfM0Z+L8pty7Ka5Xr8Xmw==,type:str]
    redirectURL: ENC[AES256_GCM,data:Ym0NkxoNj/6U91jER5/y2hnnV4BAPNSJpsKcc/nTZUZQuUxjF7QlgsQ=,iv:3bk+JcWg4IewCHsgLbKED9vnoG/uXRGr0xPCP2QhNbc=,tag:t9rjLcTtGam5/eC/Hfse1g==,type:str]
    claimUsername: ENC[AES256_GCM,data:gDUtubg=,iv:N5IY7W7yLZVrChMX9QPEGOT2FDHt65ZzuKenWYR+Kx4=,tag:Zs2cBctoNN2mULeOq+09RA==,type:str]
    claimGroups: ENC[AES256_GCM,data:mkOKcC6p,iv:KNubfUUZIsR/ZDPD7Fe80mh69K9jK2Opf+xRVdzB3zE=,tag:BL2JrmliV63E+NwMn5LenA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sph0zya56hvk004jcel0te9jk3yynx6zyq5pv0hgrs2dm6wszgssne3v8k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVGp1YzZmdVJaTDdOL0J2
            dHJCSHhCdXBkWVpqWUNaOUtyUkhHajN0S3c0Ck94Zk1XeXFFQ0lDYlViVm5oR1Iw
            QmRpV3hvcnZyWFhFT05zMzlJYnluSk0KLS0tIFA4SEYvUDc1ME9IY3UvcG9jRlhO
            UHJ5ektpZ1hvOE5CeVZQRy9YT2JaalkKrv6f7sriLPCIZPSymSgEdyuIytuhf0np
            O07CI+8sMYuMHvWGoajHb8iJn/mbdS+3YyoaigbLtLGogTRJN8Ynqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T22:29:22Z"
    mac: ENC[AES256_GCM,data:cIdS8V/2epkVl/6njWhrlaopHW+3EvuJ0Zi8OlIVwlpeeD8lX8BpN6aYwdb9c1KTKtWtlgkAc1SVRdAH08bXwtvWm4n1WsorPFR2iZjbAgJaDTP4edDcdLBrEExBXR8MIiPruDBeIcqITZq5RNAHnQ41p6cpnbXa8p/e8u4eTWY=,iv:zCbn4uLtE+0xOtgu09gYekfoOkwyN0d/hNDVF46NIlA=,tag:RgohZC6TBVSERFbSOKrp5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
