apiVersion: v1
kind: Service
metadata:
  name: vlm-vllm
  namespace: ai-agents
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/name: vlm-vllm
