---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: "16.2.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Use latest tag which is available
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "latest"

    # Authentication configuration using encrypted secret
    auth:
      existingSecret: postgresql-credentials
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
      username: authentik
      database: authentik

    # Primary PostgreSQL configuration
    primary:
      # Persistent storage configuration
      persistence:
        enabled: true
        size: 20Gi
        storageClass: ""  # Use default storage class

      # Service configuration for internal access
      service:
        type: ClusterIP
        ports:
          postgresql: 5432

      # Resource limits (optional, adjust as needed)
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"

    # Metrics configuration (optional)
    metrics:
      enabled: false
