apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: database
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:oUTM6+KCQetfgX5ymCmZAgE5WUAVxOYfkTfbymEMncbl2mnwUFhhxNIJXkM=,iv:Q+d28et7dN9kpo+jIgjiJ7g2XFKe17/Cm0G/8l/53JI=,tag:+QtNFlbmorBUSM2O45WtOg==,type:str]
    username: ENC[AES256_GCM,data:ZclFUU7E11gx,iv:ubOtDwKD27bUz+iZu98nJQWhe9WD/iOVG0s7OtdbZ78=,tag:OyTejniHnwzvB5mVof6rvw==,type:str]
    password: ENC[AES256_GCM,data:z4uSRfc4YPaa6FdppSOFD6F4zE6/TD7NfcJutH+s33subR6ELQK+JOrCB0c=,iv:3yrK4ac0XFG17/tYPAuzDy/URNdt1dtXQ8hhdfU7/g0=,tag:Wi8Ti7jd06g9O6dF7JVCrw==,type:str]
    database: ENC[AES256_GCM,data:+4sdfKj6m37N,iv:ipZMpNzB82FyHk5cpd9kSgMjdFsQKLR6tuV3hqhPXzE=,tag:cCRwsCy9NaMzHw2tttYVdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaktEYU1ORDNxd3VYWEdE
            QkR6ZkR0NFNGa1JtWm9rdTdjZ3d4RTRncVhBCmVzZFZ6WW5PYnA2NkxybktyOHJk
            djRaVDR3cFNDQUpKVHVINHkxSm9yN00KLS0tIEtTVHZDRkROeDV1R21vWFZxTUti
            aHJGcXBGUDdKMm05K2FqcVdQY0NhMjAK9EpaNO8EZRsw9vZ7+zhm5Wz+MMR9fCY/
            Ff6swIebKfOkDs++KuajA39uVHdNTOBh6WIEo2Sv3Q7dDmZRCaUi6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T03:34:03Z"
    mac: ENC[AES256_GCM,data:N/UxnTJ/efQr32H1gEpeG3xslVCOHPklLlsUwXew2vZozntyeCfcBf+0s2wYIEOqRS/gCKdnpdM+P98oHpXjx9WjD/YGzNVoMXaAvY3wWBGVlNzxOSaVDTOWoL+eJ1dWFuHTRuFNIbL/JJw1RiO+7YoPBfT++CWiGIkvTQMsqss=,iv:Cbpa66rTtXkFYBkkkK19Dfg6hdBLTUoHNMTvRYyAdCc=,tag:zkM3Hh5sJNFN4VSMH5l0Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
