apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.yaml
  - netpol-monitoring.yaml
  - netpol-vllm.yaml
  - netpol-database.yaml
  - netpol-cache.yaml
  - netpol-temporal.yaml
  - coredns-split-horizon.yaml
