apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Ec810PldQ61s+oLkGONZdW6Kx2/k/S1RoRnu6/twhbsFCpLR8Yoa6Q==,iv:sYtOa+lsNBXvhYWrK/XnP9BMu2hzLIhXeCxhL6fungo=,tag:mzYI228yPqUVMtpvh4OPvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSVB2TFc5ODhaQUtiRlV1
            NnJYNkltT3A3aDNRVG9QYnFvakdXQ2hNV1VBClR5QUVJODhicWhTYjJ5QXl4aFJ1
            RzM5QWxUVXl5NmsxUE1rRVdLS29vVlUKLS0tIEE3RVFTSm90aHFib0RIcGREbkJu
            ZXpsNnk2dWtPVXJBOEFVRVpDZHBEdmsKxGVjH+A1nbTzyS+ROlVqBCV+T28OBcDu
            6r1s1TrTcqvN6EblSZzeeY+izUBBpFOb1zjv1lB45iXT+kyxIAsrAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T23:37:54Z"
    mac: ENC[AES256_GCM,data:qdwPuaPE5SNzJjH8zdfylBk3hmRjJY/ix5dPFT9XwtFZAF7zdhXmb57NdCkUz1R1XjacUiIcr4SYJ0w+/EigmaxxDt4gGCTnieqUhncRERcRFus/a7J81iq/GfBj88efCC6batM087BgLxcjM6oZose4LMriJHrZ2O1qMrQQHog=,iv:iPRGKEjYtkru7UZrtOZS3J8WuEGMUNfKr1VYRlHtiOM=,tag:m9kJBDSAdjp2PReuVMJWlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
