apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:UloeYWQ=,iv:3L819EmFk8OcQPSNMbArsV5WnUFQb+CW0yvdLuXo62g=,tag:kTWAfX7iz8TBTMHNBy4H+A==,type:str]
    admin-password: ENC[AES256_GCM,data:VlPfuQufFVBe7E1Ydm/jH0fVzwJ5YefG+jPTzsWESRw=,iv:stpdTdfO+/ZQttTbwAwjzkyyC6wHK7iw5N1Dbp+8kuM=,tag:zPlA45tbCnKDSq6HtL732w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVlNGQXpJZk1MMzNZUTkx
            alBIOTJQaEVnWDRJblE3bElVTHpjclQ3MzFzCmswT0ljMVFzUTM0TFVQRkpwMlRV
            SGpCTWVIVXJVNWFubXhwTGpYWjZSYmMKLS0tIEN4NDlhWTRKVW1BekhPaksxZnd4
            U0dlVlYxOTkxNzNsWWtOU2FBbmU5Q3cKW4wV5hEhqzjEHpgDhRZkbUSuBmB/GEqh
            b2fQbUAF+mz1ztKsfGASVJyj9/ij3e5qgwkZcmt/eXAcQoEcZuuPZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T20:06:40Z"
    mac: ENC[AES256_GCM,data:cpddS6xS47LIlm99BOFexp1ow5qcFlJbzVQnZzXk2zTkN0wGb2sfWq+Yjv8bOZRAbMoaOk4e8ovOvphEJ/GHZKD5uQgMQXUQ/lF1mobNfv4hp1QmVWBaAM09pNpconHHJ4xufpU2bnqhfebFULXeF6tAPgx81LfxX6wdY7A8qnE=,iv:hQ+ORQN9Zc2DoqO6QBHQsEBd1bPDE6gbgtjhV+5U5Nw=,tag:8ZlqiJNcFAWzxx6KHB9fug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
