apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-gateway
  namespace: nexus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - nexus.almckay.io
    secretName: nexus-gateway-tls
  rules:
  - host: nexus.almckay.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-gateway
            port:
              number: 8000
