apiVersion: v1
kind: Service
metadata:
  name: nexus-gateway
  namespace: nexus
  labels:
    app: nexus-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: nexus-gateway
