apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexus
resources:
  - namespace.yaml
  - secret.enc.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - gateway-ingress.yaml
  - orchestrator-deployment.yaml
  - discord-listener-deployment.yaml
  - missions-migration-job.yaml
  - heartbeat-schedule-job.yaml
