apiVersion: v1
kind: Secret
metadata:
    name: nexus-config
    namespace: nexus
type: Opaque
stringData:
    redis-url: ENC[AES256_GCM,data:GOz1BJ15BtLsRe1eIPy1UGCPgnIk8M4lyU7FPSH78Y0e+Akm6iW+/JuFtpucKKT+aPB0lp3fZmOWPBP9z9fucPJvIvLSGeC471DZl+qtAVXJzDOscaq6LXjile6QN08=,iv:rz6X1tGlDO3aOXZSf89Jp8qgYSBGJqCM/yL4HuuccmA=,tag:tuNdM7wxlqyh8+e/NlrwYw==,type:str]
    nexus-database-url: ENC[AES256_GCM,data:rmLO+Ee0QrXTHOUdz2EKQJuEIzDCtsF1uCFuMt2YGOvrXS/BeBn0388LNWqWVJJIU3VfotFQ9HXqL8MCrXDX2SHJ+DborGIvFzlvI9Cn18KSeHe+Zm8=,iv:mdVZdw0eoRXD2T9f90SosGVLxFjwOiicWf5QApLg/zY=,tag:y3IP17ZIGrD44wrxWfCC7A==,type:str]
    neo4j-password: ENC[AES256_GCM,data:JiPcujXLfZk=,iv:KMFnj+vCwf1mkWQ44qHOEsD+7eYuDpL85lfJ4kwQsbo=,tag:0i+9MNXy/j0ciYLuy9uOKQ==,type:str]
    qdrant-api-key: ENC[AES256_GCM,data:P6qQuuncKaisKoD/Bi6Xvsa/mTLVFDg=,iv:MIp+JWL6lYVElwoqb5lRthNjgUTWmG0owzlN1JyWXh4=,tag:QyQkUKZ4hZjNfjSGzIcIbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMC92ZVY4alhjeWo1M21i
            d1dLaEZFOWZJQmIzRXZtd29sZFIxaDh0REZZCnNJS05XbWI4b040alp0RTU2d2NH
            WmZjbWtVaUJEUWtXMXZGTWR4SjJOb0UKLS0tIHZEOUx6dmFNM2NOUVlhNVJZdjN4
            NTFPWGtlclZZb0s2RUJmcHR1TEkva3cKWVz8Ph60UNAlhPVeJn9zzF0XKcjktbh8
            cDtQfulGmRywcT680xVlD0+HfbzzFIgzXAAwxTKT0ZCT4dlaM0PqfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T21:39:42Z"
    mac: ENC[AES256_GCM,data:nYz4FgD2Q8IBLzcqaylrTwdwxppLxYz94nEKcQIq5hVijpM4q93lx3tv+xmFTfF4Aq99A+xTtFeMJ1UjbL7o4IHKGxx9XtfIRPNvj/AjgbVucjA5m4Od8tZYzp9Bm8NQ6jFvzRrcsy9gbfwuNjzXzg9Qku+li5LqKFrj+/X3ufg=,iv:zgxOamuX4QGt6ncYFX5OsTOBVxp2eDcN6zM8mhiejco=,tag:udVyROZcdFk9HC23vTOsVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
