apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-model-api
  namespace: vllm
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - llm-fast.almckay.io
      secretName: llm-fast-tls
  rules:
    - host: llm-fast.almckay.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fast-model-api
                port:
                  number: 8000
