apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: vllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
