apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-qdrant
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/component: vector-database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: nas-qdrant-unique-id
    volumeAttributes:
      source: "//100.72.32.10/kubani/k8s-volumes/qdrant"
    nodeStageSecretRef:
      name: nas-smb-creds
      namespace: nas-storage
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
    - noperm
    - nobrl
