apiVersion: v1
kind: Secret
metadata:
    name: starbase-ghcr-pull
    namespace: starbase-system
    labels:
        app.kubernetes.io/part-of: starbase
        app.kubernetes.io/component: registry-credentials
    annotations:
        starbase.io/credential-contract: ghcr-read-packages-v1
        starbase.io/expires-on: 2026-11-23T00:00:00Z
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:zS3q2dgwvQ9CFkCPUlj9LEKI6lgfbj0/3jSubSFYs+Qtfw4Wmm2wG7XJnLjv1uvjW61imkQkqUQc6i1Tuhuy+MMiZsDiLaaczBmxUZYls52dTaXj1BxlbBMqWaIBi2ubrg==,iv:bZxAZUGSRYqn6CRggjuR/okx5cH4jPPQd2PuU2TBBbE=,tag:iY2/lJS/PgUyrqZ9wwediw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcTFBMGtWL1FNOGZMdkRY
            cnFGRE1MczNkdjN2MFF6Y2dXdVBtZlVTY2w0Cm9JU2w3SHBkdVhWcjNaWkZSbFZ3
            emt5RldxRkt1RGNxUXRlNEhkUGNvWDQKLS0tIGc0MXFHdW42SExoYkV5KzRmaEZZ
            VzkwYjB2UTBVV0JNNzV2SHkvbHpGQW8KlFu5WATZ3+d+wDa3cc4WWIzXxHwy0lf4
            pz0DiNvjFx11/gaX0owCnnmeR0kGxxAcGXlAGp0iWhK/KT/fhRMQ9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T23:22:32Z"
    mac: ENC[AES256_GCM,data:DC6slB0l5K5enWaLzaQ9RzIYRTP+oCyyMFQEyxyxhVtKVF5lz8sIOwpHhFEUMfsmzm0UPC/Afq4btm49Ki0SqyBTx8to7DfFbO1ycqwQJz2yLAjV4HoEUN8RvqLBm7YkC5F9lB36nRpqWikAYWjSqSdop1QDe0NZK26gtsBEp9Y=,iv:ZPSkdcSIjWgoPj6YrX526MYC10xusfMsZy7WGLpn3ko=,tag:9Us6zEbwKiq8w4mH+AaH2Q==,type:str]
    version: 3.13.3
