apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbase-core
  namespace: starbase-system
  annotations:
    starbase.io/activation-state: authorized-preproduction-native-observatory
    starbase.io/activation-stage: phase5-preproduction-native-observatory
spec:
  template:
    metadata:
      annotations:
        starbase.io/activation-state: authorized-preproduction-native-observatory
        starbase.io/activation-stage: phase5-preproduction-native-observatory
        starbase.io/source-revision: b3d54bc875c176dba766682a55d3bb2ca2801819 # pragma: allowlist secret
    spec:
      containers:
        - name: core
          image: ghcr.io/x-mckay/starbase/core@sha256:68385b100f24f5a28738799bc3712d6322226760a75ded14c947afbc36533345 # pragma: allowlist secret
