apiVersion: v1
kind: Secret
metadata:
    name: learning-agent-secrets
    namespace: ai-agents
type: Opaque
stringData:
    DISCORD_LEARNING_CHANNEL: ENC[AES256_GCM,data:9TZkCy6gRvF9Hp7wcnbJe11hhw==,iv:WtE6tvSBAs1hkLrYTH5QEf49ohUyZoeuyBCNI+k9YLU=,tag:4bjDt2c2o3HkeoYqVaIWcw==,type:str]
    DISCORD_APPROVALS_CHANNEL: ENC[AES256_GCM,data:kuffbAmU7/KO/t+5JwqZzBpp8g==,iv:eKqTyBmWx/ELkQr/OKU83U+/ynhkISZCjarR9ID6KmE=,tag:s2HcL+owywwHQNqfS/02yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:  # pragma: allowlist secret
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbGgvR040TmwrUHQ1U3Z4
            enVqRktsSVlEQmZlbkhwUWtBYnhhb0JKOEJVCmxRczF0eFZLcnhBUDk2RUhVLzF3
            ZU90TWtCZ2ZuR0lOTEdKNVpIVGhxVGMKLS0tIFhwcmo0S3lhUkZKOVFMTURKZHFN
            WUowTUJEODdiY3BFaGgrWlpFSzRZaVEKwT2wZMsXN0uWCJlkiN79++8u1VygRS30
            OZ3z5MwgVNqkaYkDpz3TNUdHTEdOrimH2+JLtHbIeJ1zKXjZ5L5Wkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T05:10:47Z"
    mac: ENC[AES256_GCM,data:tAoIbr0Hdqj3BJ3oBBdG/prlyy4mxNxYfxr6l9KWuMbwD4y12YkdXUR6FlkGQRvQJ3XPaCuS1h8IWjlbXxsdtFRUBP6l+lLBnegJjqp3G537Mf1soio5sPweFCobOCfQ8EA+ApObNe9x31is3tiQENB7FZaeud4kfJdjBuSM7Ug=,iv:VUt3iddnEnhUESedZoSzwL/Z0xkUrZhKxyaVeI0YaBY=,tag:AbQf9IdCJ+vDVuOm31G+3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
