apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubani-ui-ingress
  namespace: kubani-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: kubani.almckay.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubani-ui
                port:
                  number: 80
  tls:
    - hosts:
        - kubani.almckay.io
      secretName: kubani-ui-tls  # pragma: allowlist secret
