---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-agents

resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - secret.enc.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
