apiVersion: v1
kind: Secret
metadata:
    name: qdrant-mcp-server-secrets
    namespace: ai-agents
type: Opaque
stringData:
    QDRANT_API_KEY: ENC[AES256_GCM,data:DYFTL94RkhKD2y6jHe+1x4GS4/LWdIY=,iv:wN1OBH4AxnE5EkfOOQmCsBnp4KndASefItnEg4HYcZM=,tag:EJOoFtX99rkefbHDngYleg==,type:str]  # pragma: allowlist secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:  # pragma: allowlist secret
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ1g2MnhDanVaOS9aVHBj
            ZUsxajVSWTdPNzFuVzNTem80OUE3bTFQL1dZCm84SjN6b2w0MmQzeFNmc0RaazRK
            OGtiSEh3Y1pGbTNMa1duQTRmM2ovZGsKLS0tIHIxR2JNdWwvcUFtWTR6UWxuampx
            UTdsc1BjT3dUY3YyNzdESTBVL1BGK1UKPAe0aV5W1UFSu+kvu2zGqUra6a3qz0uq
            YJnlp4jOAciYcscb5zJr6J8RuMzFmOoGniT0tENvY43lWOMT7Zz1/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T04:18:37Z"
    mac: ENC[AES256_GCM,data:KrwBZg2jTyxRecAoFcJxTS9MS+qcHUT4Cj/2XW3o+mShog5HgQ8ufAunGRhRahkW5YISf7jnVBd1Em0jttkk5YGnjrDrK1m7StYHSvRIMKQ/K+5IIFyeEm8rtyeR0vRUCHljStROKyUEE+xA9lR9eShgalJBXFVNrdlSUwpxx8o=,iv:sbOLI1eETa6VuUhEJjBCcjXPNZc9yMm3QSbvXDNpM5A=,tag:fAU+HUKTet9foGHL8TXvnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
