apiVersion: v1
kind: Secret
metadata:
    name: starbase2-database
    namespace: starbase2-prod
    labels:
        app.kubernetes.io/name: starbase2
        starbase2.io/installation: starbase2-prod
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:nTszEt9fXPlpf0uT1dtxopU7V2exZ1uLX9lTJjvELiUuiIRezOKCDVceFrV3/CKyFao4jguf8/dUWETfP5FbLFvDNDEU7ot23B+bwKwAsZvjXuixFETOZfWHHWCI1khJrYU2sPPVs4k8vboLbnrY+PkARvqzdCrNWeESXyv9cn8tsQzi8POqIRRJ4jguXmJ92mK1HjD1coimnJhRccPh46TUCysQUFiF,iv:vSMf/MTsRa1Mi73YAsjKFxuMMtBV26U8AWRVjT16Ct0=,tag:MJrf9RjWG8KLiqCDLUKpOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVnJscG9rZTR5UStoRit1
            T0MrcWdlNVNMTDhYRUx2WVNWaFpOYW5YWEUwCnBWV0JEWGVUaUM4YVg3K2JYSmxw
            RVlFNHYzVzJBY3g2eGluWVVyWlJvMHcKLS0tIEJLZmxTT2JhWVdNYXhrSWJiL0dl
            OUVVNzBrWUh2dmFhcXFrdU9qZUFEc1EKgbvsBQPUFLGGXoc9fj6bQ8M1Hx1CCcoK
            FZRaYobpU1RBYztC3scg5d+YXZeh4qhSVB91d8dLORMnrlyGXw7LXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T05:51:25Z"
    mac: ENC[AES256_GCM,data:SuAWjFiDNwMen53qFxPHy6kIT6dPjS87EcPYkr5RIvrxKWVnnNvEG8SwohjRb31r3xYnAcE/KOKxSnz/v7CJ5NT8xSlsr/oanlZT0jmCHatti8UlKH6rwWLro7j97zLfPP+mao8qQ5TZD54zwys68eFVPsgGS9eTejNsA6lgQwo=,iv:3koK8eBowPD9HsJTy+gDg5wcJlifGIxlZAI4+vL4Y8w=,tag:6EroOc7MWLdFNeXodEwSTw==,type:str]
    version: 3.13.3
