apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - worker.enc.yaml
  - database.enc.yaml
  - llm-egress.yaml
  - field-resources.json
patches:
  - path: port-patch.yaml
  - path: field-patch.json
