apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../starbase-phase6-kubernetes-canary
  - github-public-https-egress.yaml

patches:
  - path: github-connector-preparation-patch.yaml
