apiVersion: v1
kind: Secret
metadata:
    name: starbase-core-migration
    namespace: starbase-system
    labels:
        app.kubernetes.io/part-of: starbase
        app.kubernetes.io/component: credentials
    annotations:
        starbase.io/credential-contract: phase4a-v1
        starbase.io/activation-state: provisioned-inactive
        starbase.io/database-transport: cluster-internal-networkpolicy-sslmode-disable
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:zxqFPmiWCudJPpkHvzZhKW+gCGbizc4HF24wbzn+e+kcGdYYoD/kGbdmL62Ra+4pl/OwVKWgLGitiHFX4QKOuk1Z3qc9R4ElNcgbL62w92Qn7LPpuFNVEuBSTJxcSDmajhDtugY+GrGo7aJGKMKuFjpzXQQPSK2eoCHvm9MBuXq6lgAOGGx+EjIn4sDSOSwiljzj6RUzg3144RglcZb/YQITBZwhH9j93anJac4JEJ0=,iv:vMxOTmiCE27odDkbiN0F6iui3X4VaPthicbzirWiabA=,tag:q09xXQRvqLkz4p1L6tpAKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMG5OdUNGSlFGZUlGVThl
            bVRzMHR1eTFGbjRQbkF2OC91YTZOaDh0WTMwCldGQ2RDY05nNjNENzI1N3M2RnFZ
            UW1DR1NzajdWTUdPRzRGQmpnbGplTUEKLS0tIGF0NDF5QXdKeHo2WnJwWDhPUmRZ
            N0xrMVpMczkrMUNUUWZpOCtUQWlqVlkK43woj13Jeu6jas0ALG7Ym1fTk7EeT4Pn
            EOtbpryw7wf4DvBuVke+nJ32/sw351/qFVWi05ZLQoIqG9W8Eo+iAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T03:06:57Z"
    mac: ENC[AES256_GCM,data:LeIFsAVGHLAV703p5f/ZgDNI3RK6vvI18gP/oVmNY4KtGeVQsstmsJe3ROfwpgAL0NO94KpFPB0RHmlP8FEA5750geAYsO5ZU/d38lA/8ES55JuyaRIjEn2MpDOW/sgttMRdPX1AbSUitGNDejH2cV14rwE+Klz+KNtf8n6k6FQ=,iv:0LGU54u6t2YFVIrDQLwXEt7RLtP7qlUpyhvDEjk4qnI=,tag:KNpbxWxV7Cc+Rz42F0AwdQ==,type:str]
    version: 3.13.3
