apiVersion: v1
kind: Secret
metadata:
    name: starbase-core-runtime
    namespace: starbase-system
    labels:
        app.kubernetes.io/part-of: starbase
        app.kubernetes.io/component: credentials
    annotations:
        starbase.io/credential-contract: phase4a-v1
        starbase.io/activation-state: provisioned-inactive
        starbase.io/database-transport: cluster-internal-networkpolicy-sslmode-disable
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:lJaaQFgeVj4tgtJCYoWY2V8n/C7kCMStEnvWtRSMYdFmkoTficxDk1GtmwuUUzLTUEB7rvjWLa/NwNildenIveMX9OJwCoo7zSitDYmR8TDwKmngdE+nt1DUrsHOsQah3t32MQ9K3x1RVVlU053f57EoNCHITrC0B3LrWRRMI5F2tq6QBZHboITco0eSg5uhjJztphW13boTuD3Nr2mxKdMWZdaTFp64HpQkFjG+3A==,iv:n/yy1VHjGFwW5vBaEd/a94kbZYlP75CAFAashko2IlE=,tag:I70XwnEzgyj9TgYNuVsKYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxN3JHVEErV2J3RUhIaGN6
            S21CMGg4cGpnZE5MUWxuWW5FY05yZEIwZGk0CnpoajY5dlVKNVpWSkVaUXV2czVK
            NGc5WkxHQzlhRFlEeG9MU2hXcWFRaEEKLS0tIGZqMU1PVTUwRzh4MElmam1Zejc0
            WmRKODNqTHY5QmM2cjFwZ1p2UUR5M2MKsC/y30UkjQfsGnG/y1oVYiKYuIudXUhh
            mgWfeNe7BEhay1DKB0lBxUqAcaxa1A7g3ebakISXDWSmgl5rTzNpfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T03:06:57Z"
    mac: ENC[AES256_GCM,data:huqpmyVjbGTelcfNZPx7cI+T0QJ1+7neTYocQTDHGou4hwFajWt3VkkDwbzHyx8drNjqhxR5liCJ62/6jw0UxaFcxworxIXPeZeDyCLumSm8X0wTGpmSVy0l9myWWF3rRkqJ67DVbZJgIiUav/1J73pIIQsshWa7N27pvDVdoCI=,iv:5NGiq47gpqd5UC18pEMBZoaVzwAYB9alsGvXRxjxHIY=,tag:j2x+C/ubxpX9IuRL7lFiYg==,type:str]
    version: 3.13.3
