apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starbase-tls
  namespace: starbase-system
  labels:
    app.kubernetes.io/part-of: starbase
  annotations:
    starbase.io/activation-state: authorized-edge-only
spec:
  secretName: starbase-tls  # pragma: allowlist secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - starbase.almckay.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starbase
  namespace: starbase-system
  labels:
    app.kubernetes.io/part-of: starbase
  annotations:
    starbase.io/activation-state: authorized-edge-only
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - starbase.almckay.io
      secretName: starbase-tls  # pragma: allowlist secret
  rules:
    - host: starbase.almckay.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: starbase-core
                port:
                  number: 80
