apiVersion: v1
kind: Secret
metadata:
    name: starbase-gateway-runtime
    namespace: starbase-system
    labels:
        app.kubernetes.io/part-of: starbase
        app.kubernetes.io/component: credentials
    annotations:
        starbase.io/credential-contract: phase4a-v1
        starbase.io/activation-state: provisioned-inactive
        starbase.io/database-transport: cluster-internal-networkpolicy-sslmode-disable
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:gFa3xCvFPeeSoU2VkGouUlOlRD9Zj116sx1eQT79c3hh85kVry7DCSUXfqjxYsfP6tSxUbohHLkMKvou3y7mo0X7XG1Tc+/bUetlNxpYnsss32nHL/yfVBBzLFT+2OM8reqql0tThLkmBWr8mi9gP6u3dq4Gs5ang+0OT1rxdq9Eg3Lvlt7bFxJk+F4fSL3Af7ELcZbanPh8vf48f+uSByGa3Sa6eHh8UVHC9WkmwUDrsIPU3ENpe6Vt,iv:tznHnANwLvu41hPhgfgFIYrCA2qaFs+bCrPOa1x9XvE=,tag:dvmQUfOuLHZIcLa0L4jxDg==,type:str]
    session-encryption-key: ENC[AES256_GCM,data:VNcFlHS8Obubwa3Is1DpDQPo/fdUBbsIGeNUkMfN8nplbDX+ph5zPagfJ0s=,iv:0GeUisiT5D/VlTB/fsxtA4OuAMoQ0VWhtRu0vMWudgc=,tag:YqIvyoPlwMTW7RnLSdqmjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcGQzQVB0Tkd1ZEVxNWpD
            UjN3dCs2c3VRN1M1cnVBQ1FzaTlLNytsYmcwCk5ub3Y1UHNBS2JkK0dZSHp1Unlv
            RTY0bk94QW5lQUZyYVdWcTRhdEFlSDAKLS0tIHVEbjdBV2ttdzExdkpkekg5R2xL
            SHhGOHU5dGxPQkJzSThJUTdtTHlQcjAKjMJMdoyFdRKXQ/kgrhskOu7JWk4QVUEr
            NMA1kcnekDtiqdMQrfV2QRRliOH6yzwtHaBq/32YgjNjl2e5bcx8Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T03:06:57Z"
    mac: ENC[AES256_GCM,data:83FZNt+/Zl+tRce/baHUuZJ/8zkBCNHapXMrA/PKMma3Q/TRT1w2Sfh56ce40m3WqeHQ3f8KJ6AWybr2igR/D5NMoy9fwQi+7108Tt+7vTuzDXs3nXQfDBBcqHWP/tmGDoMfoX8CR6Hm8uLqqfB+YuwZVOkiZ1fDXhCo6QNi5N4=,iv:0XOTnXrfO4WZMJuyOjk7yyo62vimpRANgmUz/Z08Ge8=,tag:mPAiti12TTYKCGJpsQFNKw==,type:str]
    version: 3.13.3
