apiVersion: v1
kind: Secret
metadata:
    name: starbase-gateway-migration
    namespace: starbase-system
    labels:
        app.kubernetes.io/part-of: starbase
        app.kubernetes.io/component: credentials
    annotations:
        starbase.io/credential-contract: phase4a-v1
        starbase.io/activation-state: provisioned-inactive
        starbase.io/database-transport: cluster-internal-networkpolicy-sslmode-disable
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:K3TqezQ6+g84/80mTSTo1V3scUyCQAJ0L2hgrVkoGnsxNdzpHFKEIIuYLix53pc3f+N/CbAKYjc3TjRw0ccKgMPFJ5IRbAj0zT95ZCt73BqD75JTsCN8qFLzkXAytddLzQI0f7JIykZAKu8U2P3p8zh47T4Ch7y21HzYGE6CxSvC3y3y/aPq2VrS0lGqpwdgH9JnGhAKIuePwwsLvUZSn/fTKeGFNb42MPBe9Q/uYLxfgE4XnMEvGuvTUA==,iv:WPDMnigsNjTc40HFzyxGkWBnChGosjHoUqZkocNwotY=,tag:pU81YrU6aKvUgYvn29b5GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ1JLMjRWYStkWGtXenIw
            R2ZhczM2MkVTbEprZ0l4ZmdvSloyclllTmowCjRSUS9tNXhRMXFRQVEyRFBJM0lr
            Ui9TMjZ4ZU5NZXI0MXBIaUVJYXNNTTgKLS0tIFNNNVZvTEVmaXE5d05kMjJyU1RV
            NDBBaVMyZUJXdXg3Wjd1WWxwNXJNUkkKoiXRDR3R4i8mquLBd58rLPApSLnxtFXC
            xn5CfGRLAPaWCbaKu1mriLyQEDZquRfWZFk3bMb68uP11md+S58++g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T03:06:57Z"
    mac: ENC[AES256_GCM,data:IyTTVIS2YatQAYthcjOlxzwNriqx7W/RLMZQu1VYxJP46pZDkC4DApdVFOAzPLZ2BDUoY/kdKKcUINz+E4jY++AsoawPnRmYN5ZqHDNqw29brGNuHwENTOJrhbWG3Em9nZCvc9vXuXyJTY0Hxq2yCkB4JQjjaH019vNOdGXaTDs=,iv:K1vWkahEY0qKWsTuBcD5liGYpHPEZSD8XjXXHrZNrm8=,tag:+OcBG2xwtqm0t1D6fUxCeA==,type:str]
    version: 3.13.3
