apiVersion: v1
kind: ServiceAccount
metadata:
  name: starbase-core
  namespace: starbase-system
imagePullSecrets:
  - name: starbase-ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: starbase-github-connector
  namespace: starbase-connectors
imagePullSecrets:
  - name: starbase-ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: starbase-kubernetes-connector
  namespace: starbase-connectors
imagePullSecrets:
  - name: starbase-ghcr-pull
