apiVersion: v1
kind: ResourceQuota
metadata:
  name: starbase-system
  namespace: starbase-system
  labels:
    app.kubernetes.io/part-of: starbase
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 512Mi
    limits.cpu: "3"
    limits.memory: 2Gi
    count/pods: "10"
    count/services: "4"
    count/jobs.batch: "6"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: starbase-system
  namespace: starbase-system
  labels:
    app.kubernetes.io/part-of: starbase
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 16Mi
      default:
        cpu: 250m
        memory: 128Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: starbase-connectors
  namespace: starbase-connectors
  labels:
    app.kubernetes.io/part-of: starbase
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi
    count/pods: "8"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: starbase-connectors
  namespace: starbase-connectors
  labels:
    app.kubernetes.io/part-of: starbase
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 16Mi
      default:
        cpu: 250m
        memory: 128Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: starbase-execution
  namespace: starbase-execution
  labels:
    app.kubernetes.io/part-of: starbase
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    count/pods: "12"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: starbase-execution
  namespace: starbase-execution
  labels:
    app.kubernetes.io/part-of: starbase
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      default:
        cpu: 500m
        memory: 512Mi
