---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
  namespace: temporal
spec:
  interval: 10m
  chart:
    spec:
      chart: temporal
      version: "0.45.2"
      sourceRef:
        kind: HelmRepository
        name: temporal
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Disable bundled dependencies - we use external PostgreSQL
    cassandra:
      enabled: false
    mysql:
      enabled: false
    postgresql:
      enabled: false
    elasticsearch:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false

    # Server configuration
    server:
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      config:
        persistence:
          default:
            driver: sql
            sql:
              driver: postgres12
              host: postgresql.database.svc.cluster.local
              port: 5432
              database: temporal
              user: temporal
              existingSecret: temporal-credentials
              secretName: temporal-credentials
              secretKey: postgres-password
          visibility:
            driver: sql
            sql:
              driver: postgres12
              host: postgresql.database.svc.cluster.local
              port: 5432
              database: temporal_visibility
              user: temporal
              existingSecret: temporal-credentials
              secretName: temporal-credentials
              secretKey: postgres-password

    # Admin tools
    admintools:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

    # Web UI
    web:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      service:
        type: ClusterIP
        port: 8080
      # OIDC Authentication with Authentik
      additionalEnv:
        - name: TEMPORAL_AUTH_ENABLED
          value: "true"
        - name: TEMPORAL_AUTH_PROVIDER_URL
          value: "https://auth.almckay.io/application/o/temporal/"
        - name: TEMPORAL_AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: temporal-credentials
              key: oauth-client-id
        - name: TEMPORAL_AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: temporal-credentials
              key: oauth-client-secret
        - name: TEMPORAL_AUTH_CALLBACK_URL
          value: "https://temporal.almckay.io/auth/sso/callback"

    # Schema tools for database migrations
    schema:
      setup:
        enabled: true
      update:
        enabled: true
