apiVersion: v1
kind: Secret
metadata:
    labels:
        app.kubernetes.io/component: ai-agent
        app.kubernetes.io/name: k8s-monitor
    name: k8s-monitor-secrets
    namespace: ai-agents
stringData:
    discord-webhook-url: ENC[AES256_GCM,data:Jcv6kpVKHfCh6vdlgO2nmDxfKrkftrJrbjDjWKVEcSOVhPR6o1nYYKBKfhndtGFvGSGJsjs4mGkMKItioPU5iuIPcFD2h8Uj/xJpcWlCgEa0q7dmmgRdn7m1ZZ4XcaJdGi5yOjwAfK6guacc9tn9gAnxJH0szh4zrFcOWA==,iv:lYQcRvCGLka9YPXjE3dajBwY1yEzzzvSJRC+2w1UcPM=,tag:OgF+Ee/aCqKAA0yy1kQf1Q==,type:str]
    redis-password: ENC[AES256_GCM,data:f9rAEDzqDFn7lGB3MnM1Dnfw4szL9sEehVn4y13FemW1CTW0/CHqjmg8Z9E=,iv:wnbgMn8DTeZ/2qTySyAH7+qwr2LcdV1Zm2JAHcG8pUo=,tag:8lIj+jUyKmvVLzN4oTPQbw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGlqTlpDc1R5Mi9HTmNl
            L3N6VSsrdC9oV2cxQmJHelJvclNnb0dvWjNVCmVxcTFkd2NLRmZwajZKVWV4eXFI
            UHdjWEpIMnBkVy82cGNwVTFidk1OSkEKLS0tIDZmdTdqSGYvd1ArK3I5U0N6THpU
            ZFl2a2drQ0xGblh6OE5VYjVGSGl6b1kKi8eXXvPKmwqyXavl56fa3ALiDnnnphVW
            wRBZ8R17SMqqiAGGZkeHCG9ucHZ5ABClci7MDLtX7QKNGPwhW1GS9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T18:53:00Z"
    mac: ENC[AES256_GCM,data:ZvJBzPo90Xyh76s3EuZJvXKhEreg8LqiTGy4N9HgxEZcFl7bKQ6GvsK4O/eFKD0vr/YWv0hYS1bjg4mCYR4Rwnh7z6euGmWWfrJKiWObuhDpeI2HFwagguvgJxqvJHe+RdJJ627K60swkwmQajobj8E1lNeLt+RBwnNIdRriQt4=,iv:63hbnhGrnh9jAa9F9qMtpLzZ5UDnQxJzmHx/m1s7aYU=,tag:bW6GGRtH+QO6jHYLaYbYnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
