apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-policy/
  - sources/
  - traefik/
  - cert-manager/
  - storage/
  - networking/
  - gpu-operator/
  - descheduler/
  - external-dns/
  - registry/
  - database-auth/
  - neo4j/
  - qdrant/
  - smb-csi-driver/
  - nfs-csi-driver/
  - nas-storage/
  - reloader/
  - longhorn/
