apiVersion: v1
kind: Service
metadata:
  name: web-app-frontend
  namespace: default
  labels:
    app: web-app
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: web-app
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
