---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    app.kubernetes.io/name: authentik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2024.x"
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
      interval: 12h
  dependsOn:
    - name: postgresql
      namespace: postgres
    - name: redis
      namespace: redis
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    authentik:
      secret_key: ""
      error_reporting:
        enabled: false
      postgresql:
        host: postgresql.postgres.svc.cluster.local
        port: 5432
        name: authentik
        user: authentik
        password: ""
      redis:
        host: redis-master.redis.svc.cluster.local
        port: 6379
        password: ""
    server:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      containerSecurityContext:
        runAsUser: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
    worker:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 512Mi
      containerSecurityContext:
        runAsUser: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
    postgresql:
      enabled: false
    redis:
      enabled: false
    prometheus:
      rules:
        enabled: false
      serviceMonitor:
        enabled: false
