---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgresql
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "14.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    auth:
      postgresPassword: ""
      enablePostgresUser: true
      database: default
      existingSecret: ""
    primary:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: local-path
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsNonRoot: true
      podSecurityContext:
        enabled: true
        fsGroup: 1001
    metrics:
      enabled: false
    volumePermissions:
      enabled: false
