apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../starbase-phase5-session-repair

patches:
  - path: core-kubernetes-source-patch.yaml
  - path: kubernetes-connector-canary-patch.yaml
