"""Models for the Reflection Agent."""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any
from uuid import uuid4


class InsightType(Enum):
    """Types of insights generated by reflection."""

    PATTERN = "pattern"  # Successful approaches to replicate
    ANTI_PATTERN = "anti_pattern"  # Approaches that lead to failures
    BEST_PRACTICE = "best_practice"  # General guidelines from experience
    KNOWLEDGE = "knowledge"  # Domain-specific facts and information
    SKILL_OPPORTUNITY = "skill_opportunity"  # Potential new skill


@dataclass
class ReflectionInsight:
    """An insight synthesized from cross-agent analysis."""

    # Identifiers
    insight_id: str = field(default_factory=lambda: str(uuid4()))
    insight_type: InsightType = InsightType.PATTERN

    # Content
    title: str = ""
    description: str = ""
    evidence: list[str] = field(default_factory=list)  # Execution IDs supporting this

    # Applicability
    applicable_agents: list[str] = field(default_factory=list)
    applicable_domains: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)

    # Metrics
    confidence: float = 0.0
    impact_score: float = 0.0  # How impactful this insight is
    occurrence_count: int = 0  # How many times pattern was observed

    # Metadata
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    source_evaluations: list[str] = field(default_factory=list)
    context: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage."""
        return {
            "insight_id": self.insight_id,
            "insight_type": self.insight_type.value,
            "title": self.title,
            "description": self.description,
            "evidence": self.evidence,
            "applicable_agents": self.applicable_agents,
            "applicable_domains": self.applicable_domains,
            "tags": self.tags,
            "confidence": self.confidence,
            "impact_score": self.impact_score,
            "occurrence_count": self.occurrence_count,
            "timestamp": self.timestamp.isoformat(),
            "source_evaluations": self.source_evaluations,
            "context": self.context,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ReflectionInsight":
        """Create from dictionary."""
        return cls(
            insight_id=data.get("insight_id", str(uuid4())),
            insight_type=InsightType(data.get("insight_type", "pattern")),
            title=data.get("title", ""),
            description=data.get("description", ""),
            evidence=data.get("evidence", []),
            applicable_agents=data.get("applicable_agents", []),
            applicable_domains=data.get("applicable_domains", []),
            tags=data.get("tags", []),
            confidence=data.get("confidence", 0.0),
            impact_score=data.get("impact_score", 0.0),
            occurrence_count=data.get("occurrence_count", 0),
            source_evaluations=data.get("source_evaluations", []),
            context=data.get("context", {}),
        )


@dataclass
class ReflectionResult:
    """Result of a reflection cycle."""

    # Insights discovered
    patterns: list[ReflectionInsight] = field(default_factory=list)
    anti_patterns: list[ReflectionInsight] = field(default_factory=list)
    best_practices: list[ReflectionInsight] = field(default_factory=list)
    knowledge: list[ReflectionInsight] = field(default_factory=list)
    skill_opportunities: list[ReflectionInsight] = field(default_factory=list)

    # Analysis metadata
    evaluations_analyzed: int = 0
    agents_analyzed: list[str] = field(default_factory=list)
    time_window_hours: int = 24
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))

    @property
    def all_insights(self) -> list[ReflectionInsight]:
        """Get all insights from this reflection."""
        return (
            self.patterns
            + self.anti_patterns
            + self.best_practices
            + self.knowledge
            + self.skill_opportunities
        )

    @property
    def total_insights(self) -> int:
        """Total number of insights discovered."""
        return len(self.all_insights)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "patterns": [p.to_dict() for p in self.patterns],
            "anti_patterns": [p.to_dict() for p in self.anti_patterns],
            "best_practices": [p.to_dict() for p in self.best_practices],
            "knowledge": [k.to_dict() for k in self.knowledge],
            "skill_opportunities": [s.to_dict() for s in self.skill_opportunities],
            "evaluations_analyzed": self.evaluations_analyzed,
            "agents_analyzed": self.agents_analyzed,
            "time_window_hours": self.time_window_hours,
            "timestamp": self.timestamp.isoformat(),
        }
