# This secret will hold the playit.gg agent key
# After creating, encrypt with: sops -e -i secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: playit-credentials
    namespace: minecraft
    labels:
        app.kubernetes.io/name: minecraft-bedrock
type: Opaque
stringData:
    #ENC[AES256_GCM,data:C3ClzplEMtzOiNlrICRXv+AJWMq/MRZjg+IiE2xRenjcO5BgVWOMXC41n9F4rQWI2HCJL/EsCNQ3,iv:dqiRoWPGBCPaK/pVK4QhQleJVKZWQ2kh/IulpGTD6eo=,tag:lfhfH8DUbq8k9AgnHP53kg==,type:comment]
    #ENC[AES256_GCM,data:HreIMdgFPOPJwlfxOZC5XiodiPhwfprAcd4FX7YVQ3eM,iv:81T3m4EtRgtu3sii3JvDn/2Aqpo9srtXf4LIWkBXFrs=,tag:OcN5cFFJtRHnptI3mH5MwA==,type:comment]
    secret-key: ENC[AES256_GCM,data:aMw/t0sU7IIN2jqUqVjQCmjY6ULwYj/sSpM7N21vLE0MY4tUaaDnsZ6q3sS1ME0IiUxNJEgofecMQLrgZEOhTA==,iv:ogxIDoHowTy1UPmtyiR+9hxwk4Zv+pD+xZ2Bi6kXxT4=,tag:86+87zqbv1BbBeP5E0NsJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbVBoUmpuY3FCSUFERUQ0
            czVpTkw5eTZwdFNGaTJGZ2F6aGd5ZytwNUdVCkdjQWVkM2g0eHY5ZXF5Q2V5ekZx
            a0diM2hoc05PYWFKUE5RSjZZRTkwYzAKLS0tIE8xc0w0dGdQcC83VFhlSDJpS2JE
            QVU3NFJHd1JVOWV6VE02bnEwZGh5T2sKIbdsIthcFeRm+vW+7mfN3onssMonRIWP
            /bm70GWWiiDWIrV64GVXZ9QiDDyBze7ila00xcE1mrTTX6qpxJtedA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T05:10:18Z"
    mac: ENC[AES256_GCM,data:Hl12wKh6gy7MHT1399E9iZhadStFq0o82tT9D32F3Q8cEMzxR5TLI3eogLPKanEVTY7Ydleg8Rl6p+9y8zQIJMQx31Ij/rKC+chG+fN9C4Fd/57GGJZVYYfTmIsZJJYkmKKlBLX50yh0mL7mlOC7Sll9VsZj4zIoTnasudsJ5/8=,iv:ZMexseXkgxWWh306jFcWRVM4eI/2UVozfIK1aqKg1r0=,tag:jFB6g2igTW0JQ0I02U0ffA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
