apiVersion: v1
kind: Secret
metadata:
    name: registry-basic-auth
    namespace: registry
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:rHa86LQFPIGmlLgo+odA0JIYl+iI42EOlfh5XHgCIrUHvQJ2yw+akmeOiJuMy9iNz9gVCa1duFg4v6pssZ1Q4QY2gLPactheMoQfYl2GuWnVYLmaH1bef5LqEKLwzzbPM7p2y4J19uNM2cfWFPxGAXLFJiRLtiFN8+KPRn2l9BeK9YgjKzZMiR4jaQ==,iv:aHni8NQ4BI7excBxazKrWCrUuceYATpISl8Hzs1C6I8=,tag:IrY1JCCglUlRS4qE73Q2zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPS2dFb1lFSkdidGJOZUoy
            S3pxeTY5VVlDdDMySG0vMTY2ZlRwQmJGS0MwCmN1L0dPU1JicjhmbUFlSXlDclUr
            NHNYcy9vbUJLWWVrYWR1cy84UGF0bzgKLS0tIHRHajV6VUVWUzhZNmovYVZyQmd6
            aEl2WmlxRStqL212b0JRS21DSlZIRXMK6m/NEIjaK4bwbYpe4ny74+3/gYNP8QRw
            JkVRiILawMHLP38yoL9kF35MJN/Okg3AghIHYDEoXt3nP/1aKfOevA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T01:24:53Z"
    mac: ENC[AES256_GCM,data:kKj3tX9+X10g1SzqYVMvnVu7Hd8iFtnZRSJz5LTe+JHvjm41a/3VTUyQ9qMRwWMTy5Iajl2aWQbcfJxcPEHhA+nNBYyAAxBNT6Iz9S9nKLetjvvfC0mXxCGi68hfsvk4oYSYpLStEZcfsIMdIxuTl7obQsNYG/KIsAjEy1isD9M=,iv:SRcIP77cqQa1MNwgaTEYjMXdBz2kh4QK7ajXXP+0sA8=,tag:+6/khLxvJe6K6mLQMJlGAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
