apiVersion: v1
kind: Secret
metadata:
    name: registry-basic-auth
    namespace: registry
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:AG0ZqfRk2a1M2YYc5muumi4Ehlf0inF0N72OGsB3WI1equerh8jhRpc5jDT40qKZ4rTcEovWpU34XpLmiKBXuh51bEI9CIm1DjBGELiLp/4ZF/mypA1OoZ3GnnbkKg8SKuOGNRdnMGFPjbDAUPI1Jgb5Y3ubTrjjTiknRslkMkjvezdPUOi9LwKg9w==,iv:6cdOCrlLb50QhOQ6lEhLWzxDHohjChlstDnHGdZEmWY=,tag:gTeUhN6MZjK5AqJ+5klqGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK0lvTEM5Y2hVOGpYRHZi
            N2tmQU5RaVNHN3JDbGRPaTJXQ0t3SzM3YXpRCmhmZHpwTUdnWjNiMm9qNGdsd2Ew
            Q3k4YVdkNWlkRnNUWnRCVDB5UmJGeDQKLS0tIDIwZVpUUEMrYjJaR0JCcWJWVVI5
            UTliWjFYNVY3b3dITThSSGFqdDIvclkKFfmgHvgs7qNMuSxZLalHMZgAsoAyVYB2
            H84e5NUm7FI56GQBkVSjNLHMACcskkL+ipKbodvDN3tEEbTHLZEBug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T05:34:37Z"
    mac: ENC[AES256_GCM,data:QM2Wy9ZwRTBV7CNPyDZY0EhANurMnKeObsDzku9ZwkzI2sMRhkjiE+oxyKf7w0dtt1vfJz482tcHX6mbdq7EXZH90snRHlcLK9xFWRxTSBG2T4fdECB++/uggiDVypB76T1AOun/twKMC8qa7EOmSBiRvoqrLuXl8WUyBmkCFmI=,iv:JG9IrgfRGZW7HLPuuO7eSEMDQ7PO05o2uXJDDbcOekU=,tag:jVuQEPQxAulOehsd7DZkYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
