apiVersion: v1
kind: Secret
metadata:
    name: registry-basic-auth
    namespace: registry
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:IXAL0/9vNZEHl8JAUBL2/x98dzm91oHK+rmmmaGNGTKZxoc28qHBkDSh+uFyS+kcHyX0V1LTMbPaje4+DxeQWyFfI4SgPds4foimy5s+tUmpRfS0/FAcxViV0jsmdU6Ahxbh+k4hbY8XrsI1dZ7YXLmbcWxEQf0FrRunoJjLMsRFaLYhfV1MsyQM6A==,iv:yOqaVqeNxYpYiFKquwUmsl7PWhMRWwhkdvthfdB2Qzc=,tag:46MRUk2d/4kgZWSYtL5W9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RzZuSVNVYlhGK1MvZGhp
            UGRoMlhodW9PUEZmOG9nMTdHV2FwZ1B1WVFvCkJlUHBLSitxKzNSYk9qQ2FTUTMz
            NU1yeGMvLzBFMlRNTUxmMVJlclZUSm8KLS0tIHNteTllUFg4RFQ4WGlydGtCcU5l
            VmphZDI4N0kxYmY3MUkrc054S28wVmcKMuKZLsEtqB090b/v/NAjJgD3MG1S4eg8
            r2GxZAofoeoXZDNUn/KiThCSfwNoyUGKf8jdDnIep1Xpmvi0pIn8qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T23:38:30Z"
    mac: ENC[AES256_GCM,data:Bu1yLAbxXdYCWO70zSP+fe29+TCcmD41Zh85KK9d467Gth0quF0A0sqy79ZKGTVGpXoMytq7igDWWxFdgPJtJ4wjTFRLfleGWCdjCwm9xhoEIXa6OXV3kbvZ+BpIhzT62IlnUOLbuX3dODZ8AbccilagCiCx4qWpR1JrrIreaSA=,iv:DyZP6cy6zZE54aFlJjqiwRigC6LnjLPZ7O11L/DWOZ0=,tag:TJzfRizRxkXYDfbVKDO+dw==,type:str]
    version: 3.13.3
