apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    namespace: registry
type: Opaque
stringData:
    human-username: ENC[AES256_GCM,data:r0BiVzo=,iv:qsxCJHL4ooZrBlBuc5mkdQPJYGYNMhEzTdYPI+LyTBI=,tag:jDhTSPyM+w7eBLzgM+nAhg==,type:str]
    human-password: ENC[AES256_GCM,data:LhTOmpxoxjL7v+psj6NC3y1FCkLv7Y+R1ec1ZYo3cLA=,iv:3ridqFvyJhpZ2+Q3G48qBaDfqYvi8Qy4mtVuUGspPIQ=,tag:zvFHMo4PDjjhKaWVXtO3+w==,type:str]
    automation-username: ENC[AES256_GCM,data:hMGMnY9Y3dGabQ==,iv:qIdpevLKxM/tG+oZfPqqZjjWuo1C5QeJHJYQI6AjUmQ=,tag:h4/P9vctelbM8DtXU3OLzA==,type:str]
    automation-password: ENC[AES256_GCM,data:2NL62FqI9oHD5k62MiQnNiz8NSbV8XxNElz46U1U6+0=,iv:WXTFf8rKUBjL7WsE5ddNCJJp69rcW1A1odRubJupooE=,tag:udS/P/UwZMg5cLTccSg5dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDazFTYjBlY0tSOGh2ZFM4
            RHBUYmNGc29tT0NPaHNXUkNramFXWVg3STBNCmEzV29CTWZUL1dsYW16MkV0aldt
            N1pQQjIyUzZtdDRUUHdqVy9QOEYrSmcKLS0tIHphL09nRmo3M0toN0VONENqTGlV
            dStoQnRhSFAzaGdlRFFjT2JtL0kybTgK+p/iXOd2HPBVY+9ApkMP0xuQ4TKzZ9/I
            ucaHwAREx8VkMz45QyIO6FIGdKTaQ2SudOl+uBJcMCj4U0E4jsBNzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T23:38:30Z"
    mac: ENC[AES256_GCM,data:GbFi9RinDVn2WQ1/7nJNASWBe0c5Tp3DEfG1J/ALpEvHWdC5fq7S5hpJVtmuAdqmuU+C60/T9uv07d96uofw53zRWZD1cilyyENkX3qawKbUrtWP5CLIhd7ifsl+rOl3Wlw3S5xepnaW1fkcN6QRw+rXFmpvjm+jyfJE1uwrn5c=,iv:fuayZR9j7xd+EJjCyXKCuAArVD/hgf5Low1+kUA1ZzI=,tag:QC3TReAk22iLEE2gkWgY7w==,type:str]
    version: 3.13.3
