apiVersion: v1
data:
    tls.crt: ENC[AES256_GCM,data:No9AL16uH4Vjo3VeKEi1eafMnNe953PSoAb0Xv/pM+dlLDsdkF5+NoFKQAJxUleLFlXTB1mlh5aVKxM7YzTjuLjXgvOb1kRLWDqC4yAb4InF3YhcxutzQTOxKVWG41Y8vA5gH8mMh9CT2zdenHUjUcjb9tJRwcbsuG10HALeM1h1h0c9PPBI6xyFqzGTgUkiMPjNW8D/0ua7TWg9yIxy9r2u2dIR2wcNZ+MhGiI/CfAvRzJw0YFuuIeZ421gnBJS5b/494Of8fJTO3o0iu0Llv0GIfMZqMDhwoesrZjg7E5PCk1w5b/0kW4F91nG78jOq6G39TWWnLGeZg6Ye3sR3Yonl0/HcEDesaQrAWRxKoUpMJi86xRJZ9gZstqs5X3T6JFYYVh2TNB/SK46ytbLPCnuwjxSKRzEeyAKy/mv+NdtYgnWETs9mptcDbb/C/EFZUj7c24Et532Gss/7HAJ6uJf3GgIOVEnou6lQdSDLgAPNYwNj3BhqOmwD+0/KwdvtcS0rdWZjpsOR90Gz3duGQ0Rv6k/hsjmLXmYKwO1cJmZp92PdlAD/r/Kkvqp2Lyx8aCeUpFLXK8yjiyK5R8oM2qTw69qt1W9wnHRfvafmIstqHOSZGvX3eeq7KK0QQirkfR6zMPjI2FHSMlvbP6g1vmj4M37nzUKdoCim+Q8qIv+pjEktMjOhxdLkyN46sgx/9hj79bIat65gpva3fJK+MtAiQ3u4dDUOyc2sMkIp8kT1dh58mAvDw2yo3WBc0kCqCb7e+wBv8vocJX1nN0VhMP2uJAGPQhxR84mLO/pNbGivB7EF4NK/1a509uypjzzQTtwfRAKg/CkzhAocGcDA4wutoRz8yTb/OGGVolpWEZC1Nwi+KbM2unrVUfyzjZ2sjm2X324x3wJxiHe4Lalyc1z87F3OW5s0+rOINv5hXV9z0Ov68X0d0j9MY+d2Mh8BB/YufUCYutbOgVe7Gkjl8WanTzwEQbHHVIIMmQc4WdOJTWsL9HP4HYSG6+mFRCm8YZOBbl1EAxESGOlBLNhxXgy+cc7ubKRjTolDvRdOhaYHOpF9cOKjupX6cXbPOe+h0o4fDjqBGwTQvdEcqL23lSb3Zvh78gd2TvaQXTdehRNy/UQ/06ZYYWJ8oMIEzY6ag1dXAgxtQ34lfpZ,iv:glZmxVlJ6A/UNQZW0sj6jOKiJKOOSwWrThMSRRe1XEk=,tag:p4TLsGNCM2HnYfTwvPFBYw==,type:str]
    tls.key: ENC[AES256_GCM,data:8TOzErIXETqyYdahEkGYE6iap+UTJ4zZF8mAcWyDQZpQUvFO3u0oVVVM81tFxAgu3fptUafwejpJK3MoekKabDjQzoC4GGPYk9uClbfBxe+d/MkD13GHdY1OmxVM+7OIeP6UIu6kuiInrxQ7gyFKFDZyLqV9IFvpSqSwatIPm6eoB4EscKAXyQGPpj9LzUP79t6kWh+QdoTs30jLOYHInvIejZpQHD7JPe2S7cgNEIV+Hhsy1V7W/JGqen1gHdxOSy9HBICM8JurpV6UBuzFSS5s5BaLAyjJKi0QiHT49zHz6q32fenBMBfDP39CJ27KbQS/Hym4FvZX84AYubJl1p/eO4MonbAWI2Yld6sOejebj44RVQrgMc3f1XBh8LUTJYDirskPhajHBfpnWkdnRXQhsWSFmt5p2cIcg3Kd9WuPBvu8,iv:9mLSyBMe7h9VolewmbCbJEHNmPtJrEXslZ3/Y+KgViI=,tag:Mm9ZdzfNpD4JVFUMHYdcwg==,type:str]
kind: Secret
metadata:
    name: starbase-dojo-ca
    namespace: starbase-execution
    labels:
        app.kubernetes.io/part-of: starbase
        app.kubernetes.io/component: dojo-internal-ca
    annotations:
        starbase.io/rotation-owner: Al-McKay
        starbase.io/rotate-before: "2027-09-03T22:26:07Z"
type: kubernetes.io/tls
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTkNTNlBrZmlhZ3dRVzRy
            cm1YZHRsTktORVdHTkRZZWtUZnVJdmJVVGhrCkNRT2N1Ly9SM0tSRlNubDkxdnl2
            VzRIVFZ2NGhRVlJTMWpKWFBZWHJWalkKLS0tIEZWaWJVRWwrL3lNbERQNGQ4aERq
            b2dKVGgzaUR3ZnhsWFZrcWlpTmlZV3MKLVgZdT1ROOZCPjGoyOvP5caAO2z504DA
            EXuXZyA0lQwBTo6UsJWfuxgt0YMZM7/Mo6x//Cv/wzKmmtREli5PJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T22:27:46Z"
    mac: ENC[AES256_GCM,data:CDCZYyqYt9w4awVRt3k7VFGxnqtFkf9HvkzfsOZHdtsslt9AsBpqZSF9DNHIqjgBCGJV3NoskgKeCc2asOPi+Evz9Su/CSGs8147QnaY89cSI+EaAXicrAWm92cxwjuwP5N2A501fJAc3TeyLZ6PTi2guP5eGmT+qyDihViXrTs=,iv:7xoNOO3sY/AQr/+r/k81jFH5Zbr7B07nHrC4e/RPAR8=,tag:mJHpb3wfyxwEXG/dP5XYcw==,type:str]
    version: 3.13.3
