apiVersion: v1
kind: Secret
metadata:
    name: memory-mcp-server-secrets
    namespace: ai-agents
type: Opaque
stringData:
    QDRANT_API_KEY: ENC[AES256_GCM,data:9PVRrpfz66EEzWjHgY1pfypJ5tieaf4=,iv:AH52iALESGnICt37JIZyxha73rXZCvR8BcwS4CbFpm0=,tag:jEQstujtlsD8PoLlIVRoNg==,type:str]  # pragma: allowlist secret
    NEO4J_PASSWORD: ENC[AES256_GCM,data:QGdHSuSKs5A=,iv:D+9Bl0FhvU0OuwQjS0IOZeUxYWeFUk5WjQ1uyqz/GSM=,tag:vIM0sDMjXeEyRQH4A3AG/Q==,type:str]  # pragma: allowlist secret
    REDIS_PASSWORD: ENC[AES256_GCM,data:dK8G3g1xbY6BlzyxHVk0s7Q3Za34Hqze9tgYUqGBdHMsV43j8TgFxV3wF1k=,iv:Je4sI1i/9wJh0RCD5NCAkm9+WG8wICCn4xZLaHMgASI=,tag:oA2LHtHv7YRrWt7zbSkhVg==,type:str]  # pragma: allowlist secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:  # pragma: allowlist secret
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eldoaXdVRlJJWjdyYTdC
            SnN2SDRoOTloU0FMVy9HNDlRT2xlR1BiUkU0CksrcEZrWS9uOE02YVRNVmlLVzEz
            RnRmQmF1Z3I0UW5jbi9wVHN0bEJ0ZW8KLS0tIEdoR0YvTm1jSjZrU2Zvbk92bk1X
            N0hjTDVjZ1BxTTdPdSsrVStWT0pueUkKxpr7gvvXeizb1qaclbaYgDZKd0YQg6Ec
            4E2aioJURdxOQMGqlYElyXBXekW+7UsDytOv2mOSSE4GtEH1rq7grA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T04:19:17Z"
    mac: ENC[AES256_GCM,data:tP7q83jkEq/DqkxZ607LCuGGSqOrJGIoIpTsS9nMQUVlyRug612LmoBh7iPthzJft+0r4SayCeKKrgQGDuVxHxPJhjvUm5K3ATmXkH3e3FFfuf4YBOg5GP7ZLYQs2ge+ztfg0irkAJVQ3t46V5tD7N66E7RqXQwIlGwFFSIH9Ss=,iv:517Abu7F/OP9e7LRrRyjOfXtMHeIsbvd9w1oWLoX0sA=,tag:1fDy9cLgatfHPpkVp9ch7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
