"""Nexus Skill Synthesizer.

An agent component that can autonomously create new skills based on
task requirements. When the Orchestrator encounters a task that no
existing skill can handle, it delegates to the Synthesizer.

The Synthesizer:
1. Analyzes the task requirements.
2. Generates Python skill code using the LLM.
3. Runs the code through the safety analysis pipeline.
4. Registers the skill in the registry.
5. Returns the skill for immediate use (if auto-approved).

Usage:
    from kubani.nexus.skills.synthesizer import SkillSynthesizer

    synthesizer = SkillSynthesizer(registry)
    result = await synthesizer.create_skill(
        task_description="Fetch and parse RSS feeds",
        requirements=["Handle multiple feed formats", "Return structured data"],
    )
"""

from __future__ import annotations

import json
import logging
from typing import Any

logger = logging.getLogger(__name__)

SKILL_TEMPLATE = '''"""Skill: {name}

{description}

Auto-generated by Nexus Skill Synthesizer.
"""

import json
import sys


def main(inputs: dict) -> dict:
    """Execute the skill.

    Args:
        inputs: Dict with task-specific input data.

    Returns:
        Dict with the skill's output.
    """
{body}


if __name__ == "__main__":
    import json
    inputs = json.loads(sys.stdin.read()) if not sys.stdin.isatty() else {{}}
    result = main(inputs)
    print(json.dumps(result, indent=2))
'''

SYNTHESIS_PROMPT = """You are a Python skill generator for the Kubani Nexus agent system.
Your job is to create a self-contained Python skill that accomplishes a specific task.

TASK DESCRIPTION:
{task_description}

REQUIREMENTS:
{requirements}

CONSTRAINTS:
1. The skill MUST be a single Python file with a `main(inputs: dict) -> dict` function.
2. The skill MUST NOT use subprocess, os.system, eval, exec, or any shell commands.
3. The skill MUST NOT access environment variables for secrets.
4. The skill CAN use standard library modules and common packages (requests, json, etc.).
5. The skill MUST handle errors gracefully and return structured output.
6. The skill MUST include docstrings and type hints.
7. The skill MUST be deterministic given the same inputs.
8. Keep the code concise and focused on the task.

AVAILABLE INPUTS (from the inputs dict):
- task: str — The specific task description
- context: str — Additional context from the conversation
- Any task-specific parameters

OUTPUT FORMAT:
Return a JSON object with:
- "name": str — Skill name in category/name format (e.g., "web/fetch-rss")
- "version": str — Semantic version (start with "0.1.0")
- "description": str — One-line description
- "code": str — The complete Python source code for the skill

Respond ONLY with the JSON object, no other text."""


class SkillSynthesizer:
    """Creates new skills autonomously based on task requirements.

    Attributes:
        registry: The SkillRegistry for registering new skills.
    """

    def __init__(self, registry: Any) -> None:
        self.registry = registry

    async def create_skill(
        self,
        task_description: str,
        requirements: list[str] | None = None,
        max_attempts: int = 3,
    ) -> dict[str, Any]:
        """Create a new skill based on task requirements.

        Args:
            task_description: What the skill should accomplish.
            requirements: Specific requirements for the skill.
            max_attempts: Maximum LLM generation attempts.

        Returns:
            Dict with:
                - success: bool
                - skill_id: int (if successful)
                - skill_name: str
                - status: str ('approved', 'pending_review')
                - error: str (if failed)
        """
        requirements_text = "\n".join(
            f"  - {r}" for r in (requirements or [])
        ) or "  (none specified)"

        prompt = SYNTHESIS_PROMPT.format(
            task_description=task_description,
            requirements=requirements_text,
        )

        for attempt in range(max_attempts):
            try:
                # Generate skill code via LLM
                from kubani.framework.llm import get_llm

                llm = get_llm()
                response = await llm.chat(
                    messages=[
                        {"role": "system", "content": "You are a Python code generator. Respond only with valid JSON."},
                        {"role": "user", "content": prompt},
                    ]
                )

                # Parse the response
                content = response.content.strip()
                if content.startswith("```"):
                    content = content.split("\n", 1)[1]
                    if content.endswith("```"):
                        content = content[:-3]
                    content = content.strip()

                skill_data = json.loads(content)

                name = skill_data.get("name", "generated/unknown")
                version = skill_data.get("version", "0.1.0")
                description = skill_data.get("description", task_description)
                code = skill_data.get("code", "")

                if not code:
                    logger.warning(f"Attempt {attempt + 1}: Empty code generated")
                    continue

                # Register the skill (includes safety analysis)
                skill_id = await self.registry.register(
                    name=name,
                    version=version,
                    description=description,
                    source_code=code,
                    author="nexus-synthesizer",
                    metadata={
                        "task_description": task_description,
                        "requirements": requirements or [],
                        "generation_attempt": attempt + 1,
                    },
                )

                # Check the status
                skill = await self.registry.get(name, version)
                status = skill.get("status", "unknown") if skill else "unknown"

                return {
                    "success": True,
                    "skill_id": skill_id,
                    "skill_name": name,
                    "version": version,
                    "status": status,
                    "source_code": code,
                }

            except json.JSONDecodeError as e:
                logger.warning(
                    f"Attempt {attempt + 1}: Failed to parse LLM response: {e}"
                )
            except Exception as e:
                logger.error(
                    f"Attempt {attempt + 1}: Skill synthesis failed: {e}"
                )

        return {
            "success": False,
            "error": f"Failed to synthesize skill after {max_attempts} attempts",
            "skill_name": "",
            "status": "failed",
        }
