apiVersion: v1
kind: Secret
metadata:
    name: discord-mcp-server-secrets
    namespace: ai-agents
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:1wAUI5nbs4cKtiTTPhhc7E25qQntukllWtl8wlRJnBKVYCxE75MRDErHSs0o8ZqKd0FmPnFG2rmZ+DV2Bx2tThMX0EQZ4HVQ,iv:zlgBnen/MgfWZlxPcYVkkg6/rzECTaGixBsJhK5yQDI=,tag:SQ/t9T4Hkc/boUJ7mNMxZA==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:PPKhRWqq5GiBXJ72dlqsVwJ8pA==,iv:b7UYq28IzCj0h3qGiV7dh98jEF9g+ZHXIwrduG1dBQo=,tag:CqynfLJVfR7aIIiIw1561A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:  # pragma: allowlist secret
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748  # pragma: allowlist secret
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydTJ3ZzM5bStKTTlrQVgw
            bUJGcmRVWnY2bDIxRWphanY2aTFhZ25BNWdrCnB4cTI3RGtLbnNrU2srcTE2U2wz
            RjBuRHlodnVLQURwblJ0dVUrVXZvZncKLS0tIHJqY3FDZU52T0tSdzdNbk1oTEJy
            SzdrSUR2NnkyZE1xU1IyOTFKVEFQK1EKwfZOiFmis/RUVZiZM0O/J/D1hMJuzHS9
            3iV80l28Kc1Y3kSYUymj8JyfvbKU1uk4or+Vgxrd6G4Q9hA9f0nfww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T20:58:40Z"
    mac: ENC[AES256_GCM,data:lehAUUlcvf445Yj3uACtAHYnXrqLvPw436H/vx9snmwXl+Qf2A430bhD727ZsRX2rt0mvm6XZTyxb3aMJSP8skp30jJDvJ+8/IcvUPWqptItTPtxQVrfbNAdKjNrbLnB8wnnH6L0pSHowZNMf4qfue1Aqjjo+WNib6t5+E36a2U=,iv:V95bxde8oDeg4mcdTZLhiQnqxnLK9PDpBDsCiNI+cTQ=,tag:VA/XHvOT+VYYCViZoKwzWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
