apiVersion: v1
kind: Secret
metadata:
    name: starbase-dojo-runtime
    namespace: starbase-execution
    labels:
        app.kubernetes.io/part-of: starbase
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:GCWUQdKvl6Hg5Ox7eVTY0C/XA6mX9p0iVujVMrSdTP8auKplt2f4HSsCMbRijSUx5yY+P34JoP7ISK2tVFiZoNrtSrp2k97cAcWA8CVudwCD2hqy1CUE//sYvAkZ1M81oCMFcXLfLm8VwFA4//tZKXysyiUjoffEEFBshZcJq+U5ZhHdH5Y3wHd9lVAh6goJyVvLIvlcvmtkGxgTISM2fdaqknErMY4KgAs=,iv:Kdrr9EYDTRlU9Wy02eBKzUnh6pM3EKHqovtwFpKPSU0=,tag:IazVzlnkkPmlEqef4mwwAg==,type:str]
    read-token: ENC[AES256_GCM,data:BPGXJesIXLGdfAAzFDvEaNp7Y1IQPI/WoQ95MX5IYcN4TRIZRxycckjKjreqWP8SIu4He77rR2PIWhJeeZiaCA==,iv:szQ+nRY7T3oNt3+mTFILvwYblvQGhFfD1ybSBXliwZQ=,tag:RAeIX+A28KBzECnLnUP9eA==,type:str]
    write-token: ENC[AES256_GCM,data:CsChX+cHhskF8xbMC8GvgLiXQUGCjhqwjuiMowO1Pss9wMw4yPwBVGzt2G77fQv6gcCamrvw2deKOtL8FDnEbA==,iv:mJsx9dbFRoS6qul3M7vKYZwoHfrqBG5xiXILyvb+6+w=,tag:gA2j9X76S3HXxKxDS0K61w==,type:str]
    sandbox-token: ENC[AES256_GCM,data:MD/RTjMxzS881JQ8EVrhrk/tpj6FbXPJm6cZGX3+kLMAmWQzZo+QE6OyF9od0gbKPBEvgJRpsRQxc0Sorc4FzQ==,iv:xnh7e5ZW8TXecw90BIK/bnCkHuHyaScNJhnvEuO75/M=,tag:fzPo+/8Ynb9FPUXkzqc6Hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVDl1R0xUVVoyalhoazFX
            RWt3U0Z0K1FwS0RMdm1wWTZ2d1JHc1hNNVM0CjR1NnlRTVhLa01Rb0Q0bzBMR3dX
            NkpFQ2ZSejNIN3Y0aElnVWpQWXdzb28KLS0tIHR6OW1sTTdJZXBpV1B6SXRLR0t4
            eTczaUluVEs1Q2RFOHYreDg3aEZvT2MK1vI0fYNF4q9Gc0BoI3fNOGLuLSe3hpHu
            gwhoog8kdnr02uW265j/yGwG9tXC9nTlTdf3KNJOptCKt8zq/0cfRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T21:37:46Z"
    mac: ENC[AES256_GCM,data:k5r4Wrc6yEs0Wy4kvjfhtxTS3SqFhUehowd/QaMEq8nVrq+zO24jPKkZFqoBA33hAoTDzke/IehRi8jvq9cp/1QOL+SlKxzxbgPR7aTwOEMaujBemswcVp3z8ZxRv/BHHXoBILIVjY0FCvRyfN7+OKOlNd57c4KxrI+Pa2/vqqE=,iv:Jgv67hW/xIbSBjxAd/zoc+o5jeUKbGgiRJRQuSHjHLE=,tag:krmw7P3SlEBZeW3eUCHlHA==,type:str]
    version: 3.13.3
