apiVersion: v1
kind: Secret
metadata:
    name: starbase-dojo-migration
    namespace: starbase-execution
    labels:
        app.kubernetes.io/part-of: starbase
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:ZI44l2vpNf1kyL+OZ2MG7QzNinJb+mvGDx/OdNR+kqpHeCH59U8zMz9wMjgcwKqXUlQlagFkrOsU6iTvOIdHwBKbcChf+VSx1o5qTRuoDQwBn+UtZM5m3B/zijkLdGehXZY3XCRK2IEMw+yMK/f9H25CHC7Gu22uwp23I5KxfTtQzlOqk3lX1LAc2Kcg888vMdIjMUXmuHZYuOaJFdN4KOpGU+v8NEZ1qghN,iv:0j9g44XqVQepghz6zpooGi8epPs7cVD5d3RPHjzEGqM=,tag:Ai7Or+qhQfm36dC9bQUcVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbGNMZUpmelZHT096YmdO
            T21Qdi9ZRkVIQTB0bmQ4aTJDTnpYZytWQ0dNCnpETzZjNUtKTWxTSzE3QW40U003
            MVB4eXpWZ1Nkb3pFeGJwakJxZjlPclEKLS0tIFVlNHo2OVd3elpuK2Y2czBWODl5
            RkVYWEM2SkhQUDVyOVoyTDJuRXZuVmcKQMrYpIDGLb36oLegnsoUM8XRSQEa8IM5
            BfhEVprYY79wnjh+QUe2RdG2KuYD6HXwZ9ZMwYn6TIBfJ1+p5b853A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T21:37:46Z"
    mac: ENC[AES256_GCM,data:6f/wvYpbS6dvjHaBgBu3UMgjZs3E3pqinbmlmKgOUjWcSk8YRCMwwdwoMnQc0A+MteVEARQnROXOH+SL0B0Hd01Y2d2Kkn7bjreqUd44rCCnLqHQiXf1Bduo/Ov5w0aN/jJaevwmbNJeOXsmDh/7zD7w6MPjqiPw2o7gzyYqIJc=,iv:BPI5KzBLqzeAioKIPdjaDzovY8vr1ZkT9DROvx4gKiw=,tag:AJMLjVVQIHDe9T3fxausdA==,type:str]
    version: 3.13.3
