apiVersion: v1
kind: Secret
metadata:
    name: starbase-ghcr-pull
    namespace: starbase-execution
    labels:
        app.kubernetes.io/part-of: starbase
        app.kubernetes.io/component: registry-credentials
    annotations:
        starbase.io/credential-contract: ghcr-read-packages-v1
        starbase.io/expires-on: 2026-11-23T00:00:00Z
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:vPGxybon4dPr69YSN7bzdAjZvfBSlL5MSlP8/AFa3+w2yjrVEMLx9dZzv+JfBRiMh2oBbYAdsFFyKbAexbtfNUQttQ9uwH34NJWMDQY6Hv5Ea9fVLD/0ZldrJyAvgrth8g==,iv:GsKyS9JUcv8M1zKlVmquRuwoHTL2FAq2Ggwu9u2ufKs=,tag:ZROdOSy0GDtwch7TlZbf8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdEFPY0ZWZUFRVm9KLy94
            Vy9ZUDFwOVRWMHFxOVNPU01rampuZGJLbFFVCjVBaWh4TFJkNjg5bWkwK3IwTEc5
            ditTWFFzVHNZL0MvUkdMQ2xZYTMxUDQKLS0tIDgvRFl5QVhVazJGRm5wZGhSRGxt
            QVZ6NjJMSmhGd2Vad2JCZjVnOUtsckkKzv47V4Lg3evCwOT51LqwN2ZWkGCCR28U
            GMptiQVFvvF8a0yXUu8ES4tu9QIV0lSwWndKiS3Cey/DhHheYs6fqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T21:37:46Z"
    mac: ENC[AES256_GCM,data:om5KJwyzDCSvxcjsJMQvIMY8vpqFyRCi/AqoYoHsLMHX/ZVtdOUqZ748FxUO48FvwfCeCWkL4QSwveApZCueGtj06sdAHT7rmqHadwWVgXjzAIw5D/PgqI6I5Udiwiz2vBuPoEbOy9mkhXFJgJeBvf9iI5+Q+JTpKInVFHVZPXs=,iv:0/OKyNf35e4RYJmVa2It9OSJ/pl630jkZlpZiKWiOR0=,tag:DEqf8LoI2/WqdzagnVsOig==,type:str]
    version: 3.13.3
