apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dojo-database.yaml
  - dojo-runtime.yaml
  - dojo-network-policies.yaml
  - dojo-bootstrap-secret.enc.yaml
  - dojo-runtime-secret.enc.yaml
  - dojo-migration-secret.enc.yaml
  - ghcr-pull-secret.enc.yaml
