apiVersion: v1
kind: Secret
metadata:
    name: registry-secrets
    namespace: ai-agents
    labels:
        app.kubernetes.io/name: registry
        app.kubernetes.io/component: registry-service
        app.kubernetes.io/part-of: kubani
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:+sNXwa8FXtBoEggbdbeI8Kt9syRciki/WH3p/GAXtKIfZDTIadRHV5UmnuccdCRgK9c83SczkBWz4BycNlW5nB1nmLRlgkMEiO736TnCX3zIdnejR8ysXpnuc1U1RzXfQ6SNiRlkql/RFvtYz2zsp3ZdcKPMXqnkci+rTac=,iv:glcuVcSkdy+RBielJPUSUOqjm2pL5/wAP3vi2DRYQNI=,tag:dmdFVM+drEbSkd3Wk0FLcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:  # pragma: allowlist secret
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748  # pragma: allowlist secret
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a2xtTUdqVUxVc2tFV2xk
            Q2hOcmI2QlAvOFZmbzJsTmdqbXBva0xHN0VNCmx4Q054emJFSmpVRDZqblNVR1kr
            dEQreXl5S20ybTlvcFNZZE0xdXNNbmsKLS0tIHd0ZEcwT3p3VTFpK0tPZytLV3h3
            SGVRLyt3ejl6OFIvWEtrUW1ETFpvMTgK9Dy5Oe6fCaoGUJyqjvRwNOO3mjAxMHS1
            eE7vGCVY9mLxpJPlNbOEP940Ls3dhE2+9oMGpbcZdSgruaCegGxQXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T03:45:09Z"
    mac: ENC[AES256_GCM,data:HliyOGH3XVE5udR35GqlWuv9oMg0BWSyAuDSG7/JnXBld1fwfgBnLZqkTBQDLiehdlMUR7ZAi9DvWcbydQ3TvGRaZU3wy00ho9i5u/NtGjauBJyrbvMAXg6gEI+t+iFaLRYLOPFbWoIc/yUF51A8mop3x+zxWcluTjHnR9nwhg8=,iv:RLjAgGO+3cqxbWur9cPv7XDgiUKugWc4YncI5HHLiSg=,tag:o5Opy2LI9nKVac4Lfvf+TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
