apiVersion: v1
kind: ConfigMap
metadata:
  name: starbase-dojo-ca
  namespace: starbase-system
  labels:
    app.kubernetes.io/part-of: starbase
    app.kubernetes.io/component: dojo-reader
  annotations:
    starbase.io/rotation-owner: Al-McKay
    starbase.io/rotate-before: "2027-09-03T22:26:07Z"
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBtzCCAVygAwIBAgIUESC2ixnfPZp70KLHhR9j/sr/AzswCgYIKoZIzj0EAwIw
    JzElMCMGA1UEAwwcU3RhcmJhc2UgUGhhc2UgOSBJbnRlcm5hbCBDQTAeFw0yNjA5
    MDEyMjI2MDdaFw0yNzEwMDMyMjI2MDdaMCcxJTAjBgNVBAMMHFN0YXJiYXNlIFBo
    YXNlIDkgSW50ZXJuYWwgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQeiGhP
    FXQPv0sgAmxpQDO7f/h59baRaUDM8y6dKGscMbD/EzQs6JxaFtO0zoOGmyUoVOBo
    cF4hdhoNZ+K7zb7Ro2YwZDAfBgNVHSMEGDAWgBReKbBch0Ohl1crvwo3pnyaT56D
    TzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQU
    XimwXIdDoZdXK78KN6Z8mk+eg08wCgYIKoZIzj0EAwIDSQAwRgIhAIC/lVJvOmjY
    dyrFwL+ySfiOSV7+UTmC2TgekLcyRwv9AiEAuOwvzNRMmgtx2S4RxuNPNMB/yvGY
    eYAE3Zx9TvhgHd0=
    -----END CERTIFICATE-----
