apiVersion: v1
data:
    read-token: ENC[AES256_GCM,data:VWaM8JFlmAA+vv1/wFztphT+UbHkJBwD61gscDIKZrXeNkGReyE8malMHi5kcHsdYpo9+xMGZTyeUDmdMy7g3G/ZF9yITDJtdgFZbwGV4u7gWlvfEw7flw==,iv:yotkKHiycbaYK5u87jvXVPGDFBfxpovr4aS1ape0jjw=,tag:I2cyflsIHV/nKXL/hWF7+A==,type:str]
kind: Secret
metadata:
    name: starbase-dojo-reader
    namespace: starbase-system
    labels:
        app.kubernetes.io/part-of: starbase
        app.kubernetes.io/component: dojo-reader
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMXFKbmpzbjZhRndUMnJP
            N3Y0QkFScHVOQW11eWRvQTBIcU53MUtVV0Z3CmpzK1hKR2dabXJ2cE9BcWhTYTh3
            NEI1NHNjaklHTEEyVnNxVXVRbUhGSFkKLS0tIFFJN1FPcURwNU1hT1IzL1g2SHhG
            ZHBjcTBMYVV5bitmSVZCc3BPNlByMzgKxM4d9fVXOl5sUK3Cd3ZP022FSK5ZcMIT
            1ybKywfsaR6VSFq2M+dwScH4ihOVyCs9HQeoSUA9FkurjDOFlN4odQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T22:27:46Z"
    mac: ENC[AES256_GCM,data:eSgO2hXPtHWxr8yJmjYO3JK5hbxEesqjcpwuyTV2mpzb/X6oEsj/Bllp2C1rbGZZQTYoyDyspTKFSd+d5KePm8bDlrWsNAekS1Hbs/nzQD7FmhldHLls+fjNvpjECJdOz9XVAMejfVLpQI6VJ97NQQ86FVtrg1GvR0YiHlDbwwM=,iv:ScB8OLjpTJ1oRIFrt/eDDLbclDnX29s6UXEQ59cEBtQ=,tag:yGRExYnhNXxXzubUsLEyZg==,type:str]
    version: 3.13.3
