apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-backups
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nas-backups
  resources:
    requests:
      storage: 100Gi
