apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: database
  labels:
    app.kubernetes.io/name: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
