apiVersion: v1
kind: Secret
metadata:
    name: qdrant-readonly-credentials
    namespace: database
type: Opaque
stringData:
    read-only-api-key: ENC[AES256_GCM,data:Uh1WPJKERnUXDK4G7jWUqOdikmeSlMU/YTWYD0o/HED9EtLCatXv/g==,iv:pKR9kgzOucRFC4KTuKZBxIjBtyfmy4GlqLYNwVkiA14=,tag:iGbbJ6IzJfZI5j3UhnBIFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WHgzSWg4Ny9vWVVJaGwv
            b2lqR05jaFJ0elo1R1lCK0huR0Q4UG12ZUd3CkQ1eGF3SWhvMnpNVHNGZDJsVFdF
            NEM4aWpqZ1FpSUlONC8zMk54QlFqamMKLS0tIG9CcjVRZlg4WmE2MkxjeWl2REJO
            eTlzZWlBN3lLOE9jSTJjZGpvSXlLQzQKxTdiHHWlUt+F2eKyE8uyBWTDnC3eSqVT
            PSh6BxQQe2rV1tYS7PWSFTZ2iUkNIZtNQhNg+f3xKpC6hqvk8htfpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T11:31:56Z"
    mac: ENC[AES256_GCM,data:QrcOJDdzsOALbLipGExnWJoptPnviv0l8Na+vF7kDCqRaLSK9T51eVgKcCdRRf48wjKzUkAOBqm25mrFbNDvy9cpftBlWXGK9QaOXOVxDgeyOdeERJjPyIPfzq0Q8eeJMy0l8VCK8fW5wZroaP+UWFxCcvadXIZ8nt8HKIimdbE=,iv:wtEDQf4ZsSdaNJw7Ceb/yw6BVxkpscn8fkC2Eu1iyQA=,tag:uQqCHD83LsXOiPfZNoaLeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
