apiVersion: v1
kind: Secret
metadata:
    name: qdrant-credentials
    namespace: database
    labels:
        app.kubernetes.io/name: qdrant
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:aD1Y58P2vtjTeaLhXcEbk5LkdGK0a+cFT62MLaBofjuUAObAlb4zG7z7aUKlD28q,iv:cmLLVUt4QP5NEt0j7jw7onV0wgh9NZzDZg1ITLW7mHY=,tag:HTA3c0cgLW/LILYm04MipA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENkVYd0xoMnYrN3U4UTZU
            ZFlqUy9taWV2dUcrL1MzZlhHNFNhRUFGNVhnCjRvVDVOTm9vcnJ5YVBtN2tRRWZT
            ZkJSMVdwNEFLTmdia2gxZWV1clNzcE0KLS0tIFBCYTFGQzFVYUNxRXdOL3Z4clp3
            TE5sZXRjTlBLblNibm4vcGpmNzQzV0EKngem5/q/O2SppuPa9ya2aSqxUxaU2vc9
            InNXAhezddm0PRe3mNzhgFbk5OGSzs2ERtrkMeWyEBtinTJoPy2iHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T16:36:50Z"
    mac: ENC[AES256_GCM,data:Q8FC8n+SlcIccCrU2Xmhr6ZCpGNDJfazLBfnNqueKhvhPaXPdKr6rn8h+TU7u7f22e+W5UhIG25xV4lUupD2DV8i6yJ4UPSjrW/I5UzAhn7vETwKWWuOrgO8HxxBW+3Zb5LJsLYtj5T2oVrDrdwbUMqZ49uz011w/gXjz8Eg4Z8=,iv:AhMWUasPe8c/lLQE4ByGuK1WZtgI+VbqVgdX/dCe4uA=,tag:+cXz41j4JnbwtTEt3PL9Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
