apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: kubani
  app.kubernetes.io/managed-by: flux
