apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: database
  labels:
    app.kubernetes.io/name: neo4j
spec:
  type: ClusterIP
  ports:
    - name: bolt
      port: 7687
      targetPort: bolt
      protocol: TCP
    - name: http
      port: 7474
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: neo4j
