apiVersion: v1
kind: Secret
metadata:
    name: gpu-broker-admin
    namespace: vllm
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:Ulobl4y6JmCDXCFgDRMrcyOmbuJHhCIdyVgXTW6XD7gwpEioIEtfR1SPc0DTqWIe,iv:fvEWCmO0wrqOj/YtGNMtcZNwTe64QtrsRuFV75KMipg=,tag:dvgGrAye8fvYaviZqYUDQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b0hCRWxieTJJbGJVdDZv
            WmVKYVdCd3BCcjVicWpiaytnQ0hQTmJzdmdBCmVyVFVTNmR3anp3SFE4N3NycWNa
            eW5RS1ppV1BBOWI1MGxhdWgvLzFnSmcKLS0tIHNvcG9hdWJQZjJaTkNnS2VVUU5t
            V3F0SXp4ek5keDVBTUhPL1RsRGNqdzgKapO9521e3hYqX6rtQNkTOnOImwEEqOEy
            +xLerd5/EZdpksFX9gCCvjVQOH0zrNbhUe1ICgAqUUREtXgHmKLatw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T20:12:14Z"
    mac: ENC[AES256_GCM,data:nzrtKKyGdSERxM4SHryrjVdSGibz+LQdpzIFBuRzvhcescVIkijSq3/VtrjW93ZL+iXNtguVvtsYm9EhLYTCwgqAqPsYonPWviikNi2q3ISInvjAa+6eO5J78uROAJ/tUDjnnvZdxrtK+bUBV0s0FPJcw5aVzMiGmVCX4TQQbdE=,iv:GZ79gMXBwkCh59Ekm3Esz5LfnHQ/613YxagSj8uHrXU=,tag:ErMp1WiGPxso6OqSZeDQ5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
