apiVersion: v1
kind: Secret
metadata:
    name: hf-token
    namespace: vllm
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:e2aGPR5uYK5NX7H/7av360u0LLkQDlUUp2OStsZD48TCJA/n/A==,iv:rWdQnaNoshuIT5R1kzaft1SApOnqUXii75TlVETk3Bk=,tag:9oNn3nwRidMOgmFAUrNOIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1852q0tkqzvesyz9r77cpkj4707lt60elrrmydkysf78a63j8rdaqeel748
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia09mN1RIN3dCa1Ftc3FY
            UDZ6TGxybXZZYXFLYm92UmlveDAzakxPSFhJCkZiZExjUEo2eUVIOU5LYVN6NVdu
            RFcvaVJhMXNIRThCc3cwR1FOYzlrNHMKLS0tIHJ2YVYwQXM4a3E3YzlYb0VJZm9O
            Q0RQdFlkd3hlOXRMRWk2WHFqcmlHYWsKnmWwxEICV2SI9KxvrldNbgTOrWs44jI5
            A5GPMkvhErgqUCHgTpjIw2c7BR8BWdWJp7MOd1HvJiF98V9zYnrIhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T01:00:22Z"
    mac: ENC[AES256_GCM,data:+6+Dw+oQuRkEidgek8D/vo2Wj9SOTwa/P9QlV5c9lJs7wWsYvPDy+dBZaSpKvaQ8wxxsuJO0VNuFHaCZZ0MQSmSWeUIzWfuEocVQTwu0lnPQ+NEivrXQD4IhqkDYK+0S1HOsqQtQ4Wj8cee5Jjr4YWwON9d+1zAV8yly0NKLYBU=,iv:stkptB9spGvwqBV+fOSJnime+GvEHXgJp6ooAxNMUwc=,tag:87jtLuLtTOGLy6fCwXeftw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
