---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: starbase-dojo
  namespace: flux-system
  labels:
    starbase.io/activation-wave: phase9-governed-proposal-ui
spec:
  interval: 10m0s
  timeout: 10m0s
  path: ./infrastructure/gitops/apps/starbase-phase9-dojo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: databases
  healthChecks:
    - apiVersion: batch/v1
      kind: Job
      name: starbase-dojo-database-bootstrap-v1-66e26e025d98
      namespace: database
    - apiVersion: batch/v1
      kind: Job
      name: starbase-dojo-migrate-rc6-5d13884264d9
      namespace: starbase-execution
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: starbase-dojo-tls
      namespace: starbase-execution
    - apiVersion: apps/v1
      kind: Deployment
      name: starbase-dojo-runtime
      namespace: starbase-execution
    - apiVersion: apps/v1
      kind: Deployment
      name: starbase-dojo-workflow-worker
      namespace: starbase-execution
